### PR TITLE
OutboundMessagePool and MessageRetryService

### LINKED ISSUE #447: OMP should handle retries without spin waiting
OMP needs to handle message retries without spin waiting - currently, if a message fails to send it is requeued and immediately read off the queue (if there are no other messages). This causes a very high rise in CPU usage which does not drop until the message is discarded or succeeds in sending. 

A lightweight failed message component (perhaps FailedMessageQueue) is proposed which maintains and manages a queue of failed messages, sending them back to the OMP as necessary.

### PR DESCRIPTION
**Pull request by sdbondi**
## Description

When OutboundMessagePool is unable to send a message to a peer, it
forwards it to the MessageRetryService. The service will mark the
OutboundMessage as failed and add it to an internal BinaryHeap.
OutboundMessage implements ordering based on how far it is from being
scheduled to send. Once a message is scheduled to send, it will send the
message back to the OutboundMessagePool.

Each failure to send results in an exponentially increasing backoff time
in being requeued for sending, until `max_attempts` is reached at which
point the message is discarded.

Most of this services time is spent sleeping (wake on message or every second)
to avoid high cpu usage.

## Motivation and Context

Fixes #447 

## How Has This Been Tested?

Extensive unit tests and integration tests

## Types of changes

* [x] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [x] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [x] New Tests
* [x] Documentation

## Checklist:

* [x] I'm merging against the `development` branch
* [x] I ran `cargo-fmt --all` before pushing
* [ ] My change requires a change to the documentation.
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.

### CODE REVIEW

File: comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs [hunk 1]
```diff
@@ -0,0 +1,203 @@
...
+use std::{
+    collections::BinaryHeap,
+    sync::mpsc::{Receiver, RecvTimeoutError},
+    thread::{self, JoinHandle},
+    time::Duration,
+};
+use tari_utilities::message_format::MessageFormat;
+
+const LOG_TARGET: &'static str = "comms::outbound_message_service::outbound_message_pool::message_retry_pool";
+const THREAD_STACK_SIZE: usize = 512_000;
```
Comment (SWvheerden) [inline comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs]: this seems fairly large?

File: comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs [hunk 2]
```diff
@@ -0,0 +1,203 @@
...
+            match self.shutdown_signal_rx.recv_timeout(Duration::from_millis(1)) {
+                Ok(_) => break,
+                Err(RecvTimeoutError::Timeout) => {},
+                Err(RecvTimeoutError::Disconnected) => {
+                    return Err(OutboundMessagePoolError::ControlMessageSenderDisconnected)
+                },
+            }
+
+            if let Some(msg) = self.queue.peek() {
+                if !msg.is_scheduled() {
```
Comment (SWvheerden) [inline comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs]: what happens if the first message is not scheduled but the one after that is?

File: comms/src/outbound_message_service/outbound_message_pool/outbound_message_pool.rs [hunk 3]
```diff
@@ -0,0 +1,374 @@
...
+use std::{
+    sync::{
+        mpsc::{sync_channel, SyncSender},
+        Arc,
+    },
+    thread::JoinHandle,
+};
+
+/// The default number of processing worker threads that will be created by the OutboundMessageService
+pub const DEFAULT_OUTBOUND_MSG_PROCESSING_WORKERS: usize = 4;
```
Comment (SWvheerden) [inline comms/src/outbound_message_service/outbound_message_pool/outbound_message_pool.rs]: we should probably move all of these const in a single types file

File: comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs (hunk 1 above)
Comment (SWvheerden) [reply comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs]: Also should probably move both const to a types files

Comment (SWvheerden) [inline comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs]:
```suggestion
const THREAD_STACK_SIZE: usize = 512_000; //512 kb
```

File: comms/src/outbound_message_service/outbound_message_pool/outbound_message_worker.rs [hunk 4]
```diff
@@ -0,0 +1,311 @@
...
+                // Nothing received
+                Err(RecvTimeoutError::Timeout) => {},
+                // Sender disconnected before sending the shutdown signal, this is an error
+                Err(RecvTimeoutError::Disconnected) => {
+                    return Err(OutboundMessagePoolError::WorkerShutdownSignalDisconnected)
+                },
+            }
+
+            // Read any new messages to be sent.
+            if let Some(frames) = connection_try!(message_source_connection.receive(1000)) {
```
Comment (SWvheerden) [inline comms/src/outbound_message_service/outbound_message_pool/outbound_message_worker.rs]: I have this 1000 all over the place, is this the size of the packet.
Should this not rather be put inside a const somewhere in a single place?

File: comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs (hunk 2 above)
Comment (sdbondi) [reply comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs]: The ord implementation for OutboundMessage is ordered from closest to 'now' to furthest from now. BinaryHeap orders them when a message is pushed or poped, so the first in line should always be the most recent.

File: comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs (hunk 1 above)
Comment (sdbondi) [reply comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs]: It probably is large, this was done before @neonknight64 's PR, at the time I just put a value there - since all the thread consts are in files, I'm keeping it like it is - can move it out in another PR if that's the right thing to do

File: comms/src/outbound_message_service/outbound_message_pool/outbound_message_pool.rs (hunk 3 above)
Comment (sdbondi) [reply comms/src/outbound_message_service/outbound_message_pool/outbound_message_pool.rs]: Agreed

File: comms/src/outbound_message_service/outbound_message.rs [hunk 5]
```diff
@@ -1,128 +0,0 @@
...
-    pub fn number_of_retries(&self) -> u32 {
-        self.retry_count
-    }
-
-    pub fn last_retry_timestamp(&self) -> Option<DateTime<Utc>> {
-        self.last_retry_timestamp
-    }
-}
-
-// impl<T: MessageFormat> TryFrom<Frame> for OutboundMessage<T> {
```
Comment (neonknight64) [inline comms/src/outbound_message_service/outbound_message.rs]: This can probably be removed

File: comms/src/outbound_message_service/outbound_message_pool/outbound_message_worker.rs (hunk 4 above)
Comment (sdbondi) [reply comms/src/outbound_message_service/outbound_message_pool/outbound_message_worker.rs]: Nope, it's a timeout value for the connection - a constant could make it clearer but you only need look at the receive function to know what the value means - the value need only be sensible for the loop you're using it in

File: comms/src/outbound_message_service/outbound_message.rs (hunk 5 above)
Comment (sdbondi) [reply comms/src/outbound_message_service/outbound_message.rs]: Thanks - will do

File: comms/src/peer_manager/peer_storage.rs [hunk 6]
```diff
@@ -393,7 +393,7 @@ impl PeerStorage {
             .ok_or(PeerManagerError::PeerNotFoundError)?;
         peer.addresses
             .mark_message_received(net_address)
-            .map_err(|_| PeerManagerError::DataUpdateError)?;
```
Comment (neonknight64) [inline comms/src/peer_manager/peer_storage.rs]: Many of these errors are not necessarily NetAddressError

Comment (sdbondi) [reply comms/src/peer_manager/peer_storage.rs]: Actually they all were - this change helped me find an issue, as the DataUpdateError is pretty vague
