### PR TITLE
Remove panic in messaging protocol

### LINKED ISSUE #2136: Thread 'tokio-runtime-worker' panics due to changes in #2127
**Describe the bug**

'tokio-runtime-worker' thread panics due to changes brought about by #2127

Other error messages in trace logs:
```
2020-08-14 21:06:27.962673500 [c::bn::base_node_service::service] ERROR Failed to handle outbound request message: OutboundMessageError(SendError(SendError { kind: Disconnected }))
2020-08-14 21:06:27.962673500 [c::bn::base_node_service::service] ERROR Failed to handle incoming block message: CommsInterfaceError(TransportChannelError(Canceled))
```
```
2020-08-14 16:49:40.862206000 [wallet::transaction_service::service] TRACE Transaction chain monitoring protocol has ended with result Ok(Err(TransactionServiceProtocolError { id: 11114791911398901410, error: DhtOutboundError(SendError(SendError { kind: Disconnected })) }))
2020-08-14 16:49:40.862206000 [wallet::transaction_service::service] WARN  Error completing Transaction chain monitoring Protocol (Id: 11114791911398901410): DhtOutboundError(SendError(SendError { kind: Disconnected }))
```

**To Reproduce**
Steps to reproduce the behaviour:
1. 2x base nodes started up, not mining, wallets not receiving Txs
2. Txs level stress test between 2x base node wallets

**Expected behaviour**

'tokio-runtime-worker' thread should not panic

**Screenshots**

n/a

**Desktop (please complete the following information):**

Windows 10

**Smartphone (please complete the following information):**

n/a

**Additional context**

See consoles' output attached:
[panics-PR#2127.log](https://github.com/tari-project/tari/files/5077012/panics-PR.2127.log)

Trace level log files here: https://drive.google.com/open?id=1v6XiRCXxhXbXXn1BRx9KXTeh84a58ZWQ

### PR DESCRIPTION
**Pull request by sdbondi**
I'm concerned that this panic may trigger (even though as far as I can
see it shouldn't). If it does, the node will need to be restarted so it
is better not to take the risk.

_EDIT: this condition shouldn't have been a panic as multiple `OutboundProtocolExited` events for the same peer are expected in some cases and can be safely ignored_

Fixes #2136

### CODE REVIEW

**Review by philipr-za — DISMISSED** [review]
LGTM

**Comment by hansieodendaal** [comment]
I think it panicked... See #2136.

**Comment by sdbondi** [comment]
Fixes #2136

**Review by SWvheerden — APPROVED** [review]
LGTM

**Comment by hansieodendaal** [comment]
Running a system-level Txs stress test again

**Comment by hansieodendaal** [comment]
> Running a system-level Txs stress test again

**Summary**
1. System-level Txs stress test succeeded, no panic messages.
2. Reliability of Txs sending under stress conditions dramatically improved.

3232 Txs attempted (_sender logs_)
3224 Txs detected in mempool (_sender & receiver logs_)
3224 Txs detected as mined (_sender & receiver logs_)

8 Txs pending (_sender & receiver console_), (**Note:** `3232 - 3224 = 8`) reason: 
```
2020-08-17 10:00:04.248929100 [wallet::transaction_service::protocols::send_protocol] ERROR Transaction 
    (TxId: 12100097902469877390) could not be finalized. Failure error: None
2020-08-17 10:00:05.412027100 [wallet::transaction_service::service] TRACE Send Protocol for Transaction has ended 
    with result Ok(Err(TransactionServiceProtocolError { id: 12100097902469877390, error: 
    TransactionError(ValidationError("Transaction could not be finalized")) }))
2020-08-17 10:00:05.412027100 [wallet::transaction_service::service] WARN  Error completing Send Transaction Protocol 
    (Id: 12100097902469877390): TransactionError(ValidationError("Transaction could not be finalized"))
```

File: comms/src/protocol/messaging/protocol.rs [hunk 1]
```diff
@@ -195,9 +195,19 @@ impl MessagingProtocol {
...
             OutboundProtocolExited(node_id) => {
-                self.active_queues.remove(&node_id).expect(
-                    "OutboundProtocolExited event, but MessagingProtocol has no record of the outbound protocol",
+                debug!(
+                    target: LOG_TARGET,
+                    "Outbound protocol handler exited for peer `{}`",
+                    node_id.short_str()
                 );
+                if self.active_queues.remove(&node_id).is_none() {
+                    debug!(
```
Comment (stringhandler) [inline comms/src/protocol/messaging/protocol.rs:204]: nit: Maybe a warn here?

**Review by stringhandler — APPROVED** [review]
Looks good. (Untested)

File: comms/src/protocol/messaging/protocol.rs (hunk 1 above)
Comment (sdbondi) [reply comms/src/protocol/messaging/protocol.rs:204]: I don't think so - it's actually something that we'd expect from time to time because there is a race condition here. However the purpose of this is just to clean up a dead node ID / channel pair - so either way, the race condition doesn't affect that goal.
