### PR TITLE
feat: add migration to verify and fix embedded accumulated difficulty error

### LINKED ISSUE #7386: investigate broken seed => fix acc_diff db corruption
https://drive.google.com/drive/folders/1xCEyG6CTDce90tgtx98F7jOF698aD1LM?usp=sharing

The seed peer (`81236d9bc10cd5b846b02c9ce2 / 0c8b2e6f8d21ea82bcd975f60f22c2d3caa48034abd9d87cdf1b5ea86260b917`) has a corrupt database due to difference in accumulated difficulty calculation. There are a number of peers with the same issue as can be seen from the received metadata below:

Correct from peers
```
2025-08-01 11:29:26.911000492 [c::bn::chain_state_sync_service] DEBUG Received chain metadata from NodeId 'dd95ee4da91e088ebe996ecf06' #62591, Acc_diff 109557982872828093543734327521538120632041290484009528
2025-08-01 11:29:31.369164738 [c::bn::chain_state_sync_service] DEBUG Received chain metadata from NodeId 'a2175539617768767b2a43b435' #62591, Acc_diff 109557982872828093543734327521538120632041290484009528
2025-08-01 11:29:46.438322347 [c::bn::chain_state_sync_service] DEBUG Received chain metadata from NodeId 'a7f347fc2802c8508e51deeed2' #62591, Acc_diff 109557982872828093543734327521538120632041290484009528
```
Incorrect from peers
```
2025-08-01 11:29:46.776884195 [c::bn::chain_state_sync_service] DEBUG Received chain metadata from NodeId '19365c8963fdedc5c8b6cf755c' #62591, Acc_diff 5581688266353056060109980069288887106854786894508247
2025-08-01 11:29:48.718649942 [c::bn::chain_state_sync_service] DEBUG Received chain metadata from NodeId '19365c8963fdedc5c8b6cf755c' #62591, Acc_diff 5581688266353056060109980069288887106854786894508247
```
This peer
```
2025-08-01 11:29:00.149429501 [c::bn::state_machine_service::states::listening] INFO  Our local blockchain accumulated difficulty is a little behind that of the network. We're at block #62591 with an accumulated difficulty of 15501582722418642843471617345416234145592244356425024, and the network chain tip is at #62591 with an accumulated difficulty of 109557982872828093543734327521538120632041290484009528
```
Thus
- at ` #62591` acc_diff = `109557982872828093543734327521538120632041290484009528` - actual network
- at ` #62591` acc_diff = `15501582722418642843471617345416234145592244356425024` - this node
- at ` #62591` acc_diff = `5581688266353056060109980069288887106854786894508247` - other strugglers

### PR DESCRIPTION
**Pull request by hansieodendaal**
Description
---
Added migration for accumulated difficulty, as we have an embedded accumulated difficulty error in some instances of the blockchain. It runs as a background task, and will stop when the last stored chain header has been processed.

Closes #7386.

Motivation and Context
---
See #7386.

How Has This Been Tested?
---
- System-level testing migrating the broken seed node's db from v5
- System-level testing a known good db from v1
- System-level testing a known good db from v5

What process can a PR reviewer use to test or verify this change?
---
- Code review
- System-level testing 

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

## Summary by CodeRabbit

* **New Features**
  * Automatic, non-blocking background task that rebuilds accumulated difficulty data and can resume from the last processed height.
  * Public status and update endpoints to query and advance accumulated-data rebuild progress.

* **Migrations**
  * Migration version bumped; accumulated-data rebuild status is now recorded so upgrades can resume and report progress.

* **Bug Fixes**
  * Added additional known-good checkpoints to improve migration accuracy and robustness.

### CODE REVIEW

**Comment by hansieodendaal** [comment]
As per technical discussion, this PR will be changed to not roll back the db but only recalculate the accumulated difficulty table as a background task.

File: base_layer/core/src/chain_storage/blockchain_database.rs [hunk 1]
```diff
@@ -368,6 +369,83 @@ where B: BlockchainBackend
...
+                // shut down when base node shutdown is triggered
+                let res = tokio::task::spawn_blocking(move || {
+                    process_accumulated_data_for_height(db, difficulty_calculator, height)
+                })
+                .await;
+                match res {
+                    Ok(Ok(current_status)) => {
+                        last_status = current_status;
+                    },
+                    Ok(Err(e)) => {
```
Comment (MCozhusheck) [inline base_layer/core/src/chain_storage/blockchain_database.rs:418]: Maybe in a case this fails we should retry to recalculate difficulty again to make it more error prone.

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 2]
```diff
@@ -3995,3 +4115,76 @@ fn get_correct_accumulated_difficulty() -> Vec<(u64, U512)> {
     #[cfg(not(any(tari_target_network_mainnet, tari_target_network_nextnet)))]
     vec![]
 }
+
+fn get_correct_accumulated_difficulty_v5() -> Vec<(u64, U512)> {
+    #[cfg(tari_target_network_mainnet)]
+    {
+        vec![
```
Comment (stringhandler) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: Didn't review properly, but this might be a problem. It might cause nodes to rollback to one of these heights

File: base_layer/core/src/chain_storage/blockchain_database.rs (hunk 1 above)
Comment (SWvheerden) [reply base_layer/core/src/chain_storage/blockchain_database.rs:418]: I think this is fine as is, if we recalculate, what will have changed? Its kinda a big issue if this has broken.

File: base_layer/core/src/chain_storage/blockchain_database.rs [hunk 3]
```diff
@@ -2385,8 +2463,17 @@ fn get_vm_key_for_candidate_block<T: BlockchainBackend>(
     db: &mut T,
     candidate_block: Arc<Block>,
 ) -> Result<FixedHash, ChainStorageError> {
-    let vm_height = tari_rx_vm_key_height(candidate_block.header.height);
-    let mut current_header = candidate_block.header.clone();
+    get_vm_key_for_candidate_header(db, candidate_block.header.clone())
+}
+
+// this si tricky as we need to find the vm_key hash for the candidate block, but it might not be in the current chain
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/blockchain_database.rs]:
```suggestion
// this is tricky as we need to find the vm_key hash for the candidate block, but it might not be in the current chain
```

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 4]
```diff
@@ -3995,3 +4115,76 @@ fn get_correct_accumulated_difficulty() -> Vec<(u64, U512)> {
     #[cfg(not(any(tari_target_network_mainnet, tari_target_network_nextnet)))]
     vec![]
 }
+
+fn get_correct_accumulated_difficulty_v5() -> Vec<(u64, U512)> {
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: why not merge the two?

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 5]
```diff
@@ -3995,3 +4115,76 @@ fn get_correct_accumulated_difficulty() -> Vec<(u64, U512)> {
...
+    #[cfg(tari_target_network_mainnet)]
+    {
+        vec![
+            // We have known bad values at the next height, so this one can be a good reference point
+            (
+                15224,
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: we dont need this fine grained loop, rough estimates will be fine as we will fix these in the background. And it should be quick.

**Review by SWvheerden — COMMENTED** [review]
few comments here

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs (hunk 2 above)
Comment (hansieodendaal) [reply base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: It will not roll back anything, but it will trigger the accumulated difficulty to be recalculated from the last known good height onwards and be replaced in-place up to the last persisted chain header.

File: base_layer/core/src/chain_storage/blockchain_database.rs (hunk 1 above)
Comment (hansieodendaal) [reply base_layer/core/src/chain_storage/blockchain_database.rs:418]: Agreed. If it does error here, the node will retry it the next time it is restarted from the last refreshed height.

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 6]
```diff
@@ -3945,7 +4064,7 @@ pub struct OldChainTipData {
     pub total_accumulated_difficulty: U256,
 }
 
-fn get_correct_accumulated_difficulty() -> Vec<(u64, U512)> {
+fn get_correct_accumulated_difficulty_v1_and_v5() -> Vec<(u64, U512)> {
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]:
```suggestion
fn get_correct_accumulated_difficulty() -> Vec<(u64, U512)> {
```

File: base_layer/core/src/chain_storage/blockchain_database.rs [hunk 7]
```diff
@@ -2859,6 +2946,39 @@ fn process_payref_for_height<B: BlockchainBackend>(
...
 
+// Process accumulated data rebuild for the given height
+fn process_accumulated_data_for_height<B: BlockchainBackend>(
+    db: Arc<RwLock<B>>,
+    difficulty_calculator: DifficultyCalculator,
+    height: u64,
+) -> Result<AccumulatedDataRebuildStatus, ChainStorageError> {
+    debug!(target: LOG_TARGET, "[AccData] Processing accumulated data rebuilding for height {}", height);
+
+    let write_txn = db
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/blockchain_database.rs]:
```suggestion
    let write_lock = db
```

Comment (SWvheerden) [reply base_layer/core/src/chain_storage/blockchain_database.rs]: this is not a write txn, its a write_lock on the db.

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 8]
```diff
@@ -3884,7 +3909,101 @@ fn run_migrations(db: &mut LMDBDatabase) -> Result<(), ChainStorageError> {
             info!(target: LOG_TARGET, "[MIGRATIONS] v{}: PayRef migration management completed", migrate_from_version);
         }
 
-        // Lets update the migration version
+        // MIGRATION: Total accumulated difficulty migration - re-calculate accumulated difficulties from the last known
+        // good accumulated difficulty
+        if migrate_from_version == 5 {
+            let mut known_good_difficulties = get_correct_accumulated_difficulty_v1_and_v5();
+            known_good_difficulties.sort_by(|a, b| a.0.cmp(&b.0));
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]:
```suggestion
```

Comment (SWvheerden) [reply base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: its already a sorted unified list

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 9]
```diff
@@ -2879,6 +2893,39 @@ impl BlockchainBackend for LMDBDatabase {
...
+            &self.metadata_db,
+            &MetadataKey::AccumulatedDataRebuildStatus.as_u32(),
+            &MetadataValue::AccumulatedDataRebuildStatus(status.clone()),
+            None,
+        )?;
+
+        write_txn.commit()?;
+
+        Ok(status)
+    }
```
[the remark this answers is not in the document]
Comment (hansieodendaal) [reply base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: All consistency gaurantees are upheld in the calling function, `fn process_accumulated_data_for_height<B: BlockchainBackend>(` as this code is only used for a once-off migration. This code only runs if we have existing `ChainHeder` data in the lmdb, which includes the `BlockHeaderAccumulatedData`.

**Review by SWvheerden — APPROVED** [review]
