### PR TITLE
feat!: fix difficulty overflow

### LINKED ISSUE #5851: Total achieved difficulty is stored in u64
Total difficulty achieved is stored in a u64. This should be much larger as this will overflow at one point or another. Recommended is u256 for individual targets and something larger for the compared chain difficulty

### PR DESCRIPTION
**Pull request by SWvheerden**
Description
---
Increases the accumulated algo difficulty from u64 ti u128. 
Increases the total accumulated difficulty from u128 to u256. 

Motivation and Context
---
Having block difficulty as u64 and accumulated difficulty as u64 will overflow.
See:  https://github.com/tari-project/tari/issues/5851

How Has This Been Tested?
---
unit tests

Fixes: https://github.com/tari-project/tari/issues/5851

### CODE REVIEW

File: base_layer/core/src/base_node/chain_metadata_service/service.rs [hunk 1]
```diff
@@ -303,7 +305,7 @@ mod test {
         });
 
         service.update_liveness_chain_metadata().await.unwrap();
-
+        //
```
Comment (AaronFeickert) [inline base_layer/core/src/base_node/chain_metadata_service/service.rs]:
```suggestion
```

File: base_layer/core/src/base_node/proto/chain_metadata.rs [hunk 2]
```diff
@@ -33,18 +31,15 @@ impl TryFrom<proto::ChainMetadata> for ChainMetadata {
     type Error = String;
 
     fn try_from(metadata: proto::ChainMetadata) -> Result<Self, Self::Error> {
-        const ACC_DIFFICULTY_ARRAY_LEN: usize = mem::size_of::<u128>();
-        if metadata.accumulated_difficulty.len() != ACC_DIFFICULTY_ARRAY_LEN {
+        if metadata.accumulated_difficulty.len() != 32 {
```
Comment (AaronFeickert) [inline base_layer/core/src/base_node/proto/chain_metadata.rs]: Might be prudent to define a `const` for the encoding length since it's used in several places and needs to be consistent.

File: base_layer/core/src/proof_of_work/accumulated_difficulty.rs [hunk 3]
```diff
@@ -0,0 +1,216 @@
...
+impl AccumulatedDifficulty {
+    /// A const constructor for Difficulty
+    pub fn from_u128(d: u128) -> Result<Self, DifficultyError> {
+        if d < u128::from(MIN_DIFFICULTY) {
+            return Err(DifficultyError::InvalidDifficulty);
+        }
+        Ok(Self(d))
+    }
+
+    /// Return the difficulty as a u64
```
Comment (AaronFeickert) [inline base_layer/core/src/proof_of_work/accumulated_difficulty.rs]:
```suggestion
    /// Return the difficulty as a `u128`
```

File: applications/minotari_app_grpc/src/conversions/chain_metadata.rs [hunk 4]
```diff
@@ -26,12 +26,13 @@ use crate::tari_rpc as grpc;
 
 impl From<ChainMetadata> for grpc::MetaData {
     fn from(meta: ChainMetadata) -> Self {
-        let diff = meta.accumulated_difficulty();
+        let mut diff = [0u8; 32];
+        meta.accumulated_difficulty().to_big_endian(&mut diff);
```
Comment (AaronFeickert) [inline applications/minotari_app_grpc/src/conversions/chain_metadata.rs:30]: This pattern appears in several places. Would it make sense to refactor it out to its own type and expose this via `to_bytes`?

File: base_layer/core/src/base_node/proto/chain_metadata.rs [hunk 5]
```diff
@@ -33,18 +31,15 @@ impl TryFrom<proto::ChainMetadata> for ChainMetadata {
...
-                ACC_DIFFICULTY_ARRAY_LEN,
+                32,
                 metadata.accumulated_difficulty.len()
             ));
         }
 
-        let mut acc_diff = [0; ACC_DIFFICULTY_ARRAY_LEN];
-        acc_diff.copy_from_slice(&metadata.accumulated_difficulty[0..ACC_DIFFICULTY_ARRAY_LEN]);
-        let accumulated_difficulty = u128::from_be_bytes(acc_diff);
+        let accumulated_difficulty = U256::from_big_endian(&metadata.accumulated_difficulty);
```
Comment (AaronFeickert) [inline base_layer/core/src/base_node/proto/chain_metadata.rs:43]: Type refactoring could make this cleaner via a `from_bytes`.

File: base_layer/core/src/proof_of_work/accumulated_difficulty.rs [hunk 6]
```diff
@@ -0,0 +1,216 @@
...
+    pub fn max() -> AccumulatedDifficulty {
+        AccumulatedDifficulty(u128::MAX)
+    }
+
+    pub fn checked_add_difficulty(&self, d: Difficulty) -> Option<AccumulatedDifficulty> {
+        let difficulty = d.as_u64() as u128;
+        if u128::MAX - difficulty < self.0 {
+            return None;
+        }
+        Some(AccumulatedDifficulty(self.0 + difficulty))
```
Comment (AaronFeickert) [inline base_layer/core/src/proof_of_work/accumulated_difficulty.rs]: Can't this be done [directly](https://doc.rust-lang.org/std/primitive.u128.html#method.checked_add) using `checked_add`?

File: base_layer/core/src/proto/block.rs [hunk 7]
```diff
@@ -14,21 +14,25 @@
 //
 // THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 // INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTcAL,
```
Comment (AaronFeickert) [inline base_layer/core/src/proto/block.rs]:
```suggestion
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
```

File: base_layer/core/src/proof_of_work/accumulated_difficulty.rs [hunk 8]
```diff
@@ -0,0 +1,216 @@
...
+        AccumulatedDifficulty(MIN_DIFFICULTY.into())
+    }
+
+    /// Maximum Difficulty
+    pub fn max() -> AccumulatedDifficulty {
+        AccumulatedDifficulty(u128::MAX)
+    }
+
+    pub fn checked_add_difficulty(&self, d: Difficulty) -> Option<AccumulatedDifficulty> {
+        let difficulty = d.as_u64() as u128;
```
Comment (AaronFeickert) [inline base_layer/core/src/proof_of_work/accumulated_difficulty.rs]: This seems to upset `clippy`, but it's easy enough to use `u128::from(d.as_u64())` so the intent is clear.

**Review by AaronFeickert — CHANGES_REQUESTED** [review]

File: applications/minotari_app_grpc/src/conversions/chain_metadata.rs (hunk 4 above)
Comment (SWvheerden) [reply applications/minotari_app_grpc/src/conversions/chain_metadata.rs:30]: I dont think its worth creating a new wrapper around U256 just so we can have to_bytes().

File: base_layer/core/src/base_node/proto/chain_metadata.rs (hunk 5 above)
Comment (SWvheerden) [reply base_layer/core/src/base_node/proto/chain_metadata.rs:43]: See above, still dont think its worth creating an entire new wrapper just for these two functions.

File: base_layer/core/src/proof_of_work/accumulated_difficulty.rs (hunk 6 above)
Comment (SWvheerden) [reply base_layer/core/src/proof_of_work/accumulated_difficulty.rs]: yip this was left over as AccumulatedDifficulty was a u256 which does not have checked_add.

**Review by AaronFeickert — APPROVED** [review]
LGTM
