### PR TITLE
fix: console wallet address display overrun

### LINKED ISSUE #7560: Payment id address are too long to be properly displayed in the console wallet
These address are too long, and we need to cut them off with a `...` when displaying them in the main view of the console wallet

Image

### PR DESCRIPTION
**Pull request by hansieodendaal**
Description
---
Fixed console wallet address display in the transactions tab to not overrun its display area for pending and completed transactions.

Fixes #7560.

Motivation and Context
---
See #7560.

How Has This Been Tested?
---
System-level testing using extra-long payment_id addresses:

image

What process can a PR reviewer use to test or verify this change?
---
Code review
System-level testing 

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved address display in transaction lists with consistent truncation for better readability.
  * Enhanced handling of offline payment addresses to display as "Offline payment" instead of raw address data.

* **Refactor**
  * Reorganized address formatting logic for transaction views.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: applications/minotari_console_wallet/src/automation/commands.rs [hunk 1]
```diff
@@ -151,6 +151,7 @@ pub(crate) const SPEND_STEP_2_SELF: &str = "step_2_for_self";
 pub(crate) const SPEND_STEP_3_SELF: &str = "step_3_for_self";
 pub(crate) const SPEND_STEP_3_PARTIES: &str = "step_3_for_parties";
 pub(crate) const SPEND_STEP_4_LEADER: &str = "step_4_for_leader_from_";
+// 182pdTyFugJYu7vDc1z7bU1t6KvoqzvKxwbfw1AcYK7X63xduDvSHsezfNgKY5xjEX4EYnC5zoqLVTv2xfzhFYgpVBMxnMyuS
```
Comment (SWvheerden) [inline applications/minotari_console_wallet/src/automation/commands.rs]:
```suggestion
```

**Review by SWvheerden — APPROVED** [review]
