### PR TITLE
fix: multi_address_with_stats merging to only retain the newest valid claims in the peer_db

### LINKED ISSUE #7491: MultiaddressesWithStats merging is wrong
Currently the addresses are just merged together, and new addresses are added. We should be more clever with this, and only allow the newest signed advertised addresses. 
We should compare the date and only use new valid addresses. Currently we accumulate old invalid addresses from peers.

### PR DESCRIPTION
**Pull request by hansieodendaal**
Description
---
The peer_db now only retains the latest claims, and peer multi-address merges cleans out old data.

Closes #7491.

Motivation and Context
---
See #7491.

How Has This Been Tested?
---
Added new unit tests:
- MultiAddressWithStats
  - `fn it_merges_addresses_with_stats_correctly()`
  - `fn it_merges_when_config_overlaps()`
  - `fn it_prefers_advertised_addresses_over_config_on_tie()`
- PeerManager
  - `async fn it_correctly_merges_old_and_new_address_claims()`

System-level testing.

What process can a PR reviewer use to test or verify this change?
---
Code review.
System-level testing.

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

## Summary by CodeRabbit

- New Features
  - Claim-aware peer address merging that prefers newer signed claims, preserves configured addresses, enforces capacity limits, and deterministically breaks ties in favor of advertised addresses.
  - Batch-style address updates with automatic pruning of stale addresses to keep peers’ address lists current.

- Bug Fixes
  - Eliminates inconsistent ordering, duplicates, and outdated addresses after updates; preserves and propagates usage/latency stats correctly.

- Documentation
  - Clarified merge, replacement, and tie-breaking behavior.

- Tests
  - Added tests for claim timestamps, merge scenarios, tie-breaking, config overlap, and database consistency.

### CODE REVIEW

File: comms/core/src/net_address/mutliaddresses_with_stats.rs [hunk 1]
```diff
@@ -129,8 +109,65 @@ impl MultiaddressesWithStats {
...
-        for addr in &other.addresses {
+    /// Merges another set of addresses into this set, preserving usage stats where possible.
+    ///
+    /// Merge logic:
+    /// - If the incoming set has a strictly newer signed claim, all non-config addresses are replaced by the incoming
+    ///   set.
+    /// - If the incoming set is older, only usage stats for known addresses are updated.
+    /// - If neither set has a signed claim or timestamps are equal, addresses are merged individually.
+    ///
+    /// After merging, addresses are sorted by quality and truncated to the maximum allowed.
```
Comment (SWvheerden) [inline comms/core/src/net_address/mutliaddresses_with_stats.rs:122]: 2 questions here, quick one whould we ever get non-signed addresses? And is this not a security issue?

And then the other one, why are we filtering on the config also here?
Zooming out, I get its a manually inserted address, but if the node does not even advertise that addresses a connectable address, why keep it in there if its not dialable?

Comment (hansieodendaal) [reply comms/core/src/net_address/mutliaddresses_with_stats.rs:122]: I re-organized the last branch a bit and added better explanatory comments. 

A non-signed address source can only come from config; all other sources contain a claim with a signature that is validated and accepted or rejected. This function caters for all permutations and combinations:
- Incoming is newer -> replace but do not throw away addresses from config
- Incoming is older  -> only update stats for known addresses
- Incoming has the same time stamp -> address-by-address merge
- Either one or both is from config -> address-by-address merge

We keep the config addresses around until we do the actual merge, then the best source is chosen - an identity claim will trump a config source.

**Review by SWvheerden — APPROVED** [review]
