### PR TITLE
fix: remove statement from sparse Merkle tree proofs

### LINKED ISSUE #5527: Sparse Merkle tree proofs include statement
Sparse Merkle trees and related proofs were added in #5457, though they aren't yet used in any consensus-related applications.

The [proof structure](https://github.com/tari-project/tari/blob/2e400836111c14fdfc52d84e5a64bbbb2d438956/base_layer/mmr/src/sparse_merkle_tree/proofs.rs#L20-L26) for both inclusion and exclusion proofs includes the key and value hashes for the node in question, which means it effectively includes part of the proof statement (it does not include the root hash).

This seems like a bit of bad code smell. For both [inclusion](https://github.com/tari-project/tari/blob/2e400836111c14fdfc52d84e5a64bbbb2d438956/base_layer/mmr/src/sparse_merkle_tree/proofs.rs#L69-L78) and [exclusion](https://github.com/tari-project/tari/blob/2e400836111c14fdfc52d84e5a64bbbb2d438956/base_layer/mmr/src/sparse_merkle_tree/proofs.rs#L80-L84) proofs, the verifier provides the root hash and node key hash. For inclusion proofs, the verifier additionally provides the expected value hash; this is implicit for exclusion proofs. This requires that the verifier check the consistency of the provided data with that of the proof, which seems unnecessary. Additionally, one could imagine cases where an implementation mistakenly assumes the validity of the statement data within a proof provided by a malicious prover.

A more idiomatic approach would be to remove the key and value hashes from the proof and have them be provided solely by the verifier.

### PR DESCRIPTION
**Pull request by SWvheerden**
Description
---
Removes the key and value hashes from sparse Merkle tree proofs. Adds a path check to inclusion proof verification. Closes #5527.

Motivation and Context
---
Currently, sparse Merkle tree proofs [include](https://github.com/tari-project/tari/blob/87c070305951152c62a0179e13fadc55065cc318/base_layer/mmr/src/sparse_merkle_tree/proofs.rs#L23-L24) the key and value hashes for the proof. As these are effectively the proof statement, it doesn't really make sense to include them in the proof structure.

Including them means additional work for the verifier for both [inclusion](https://github.com/tari-project/tari/blob/87c070305951152c62a0179e13fadc55065cc318/base_layer/mmr/src/sparse_merkle_tree/proofs.rs#L75-L76) and [exclusion](https://github.com/tari-project/tari/blob/87c070305951152c62a0179e13fadc55065cc318/base_layer/mmr/src/sparse_merkle_tree/proofs.rs#L83) proofs that isn't needed. This design also seems like a footgun that could lead an implementer to unintentionally trust the statement from a malicious prover.

This PR removes the key and value hashes from the proof structure altogether, and updates relevant functions accordingly. It also adds a path check to the inclusion proof verifier for consistency with the exclusion proof verifier, which may also help with faster detection of invalid proofs.

How Has This Been Tested?
---
Existing tests pass.

What process can a PR reviewer use to test or verify this change?
---
Check that the new verification logic is correct.

Breaking Changes
---
None. While this changes the structure of sparse Merkle tree proofs, they are not currently used and do not have serialization defined.

### CODE REVIEW

**Review by CjS77 — APPROVED** [review]

File: base_layer/mmr/src/sparse_merkle_tree/node.rs [hunk 1]
```diff
@@ -110,7 +109,72 @@ hash_type!(NodeHash);
...
+        if self.cursor_front >= self.cursor_back {
+            return None;
+        }
+        self.cursor_back -= 1;
+        let bit = get_bit(self.key.as_slice(), self.cursor_back);
+        Some(bit_to_dir(bit))
+    }
+
+    fn nth_back(&mut self, n: usize) -> Option<Self::Item> {
+        self.cursor_back -= n;
```
Comment (sdbondi) [inline base_layer/mmr/src/sparse_merkle_tree/node.rs:168]: Could underflow. Should check for this case and return None.

Comment (CjS77) [reply base_layer/mmr/src/sparse_merkle_tree/node.rs:168]: Good catch
