### PR TITLE
fix: add hidden types and seed words to key manager

### LINKED ISSUE #4861: `Mnemonic::to_mnemonic` should wrap the seed words in Zeroizing
https://github.com/tari-project/tari/blob/5b0eb0459c7d29a25339c22a289153d27d57388e/base_layer/key_manager/src/mnemonic.rs#L254

The TariSeedWords ffi struct may need to be updated, but I don't think this will cause a breaking change as it will not change the underlying representation

### PR DESCRIPTION
**Pull request by jorgeantonio21**
Description
---
We refactor the `key_manager` crate so that hides sensitive data such as mnemonics, encryption and mac keys, etc.

Motivation and Context
---
Tackle issue #4861 and a portion of #4846.

Fixes #4861 

How Has This Been Tested?
---
Add unit tests for `SeedWords`. Also generated need wallet with visible seed words, to the user.

### CODE REVIEW

**Review by stringhandler — DISMISSED** [review]
Looks great

File: base_layer/key_manager/src/lib.rs [hunk 1]
```diff
@@ -30,3 +38,31 @@ pub(crate) fn mac_domain_hasher<D: Digest + LengthExtensionAttackResistant>(
...
+
+#[derive(Debug, Clone)]
+pub struct SeedWords {
+    words: Vec<Hidden<String>>,
+}
+
+impl SeedWords {
+    pub fn new(words: &[String]) -> Self {
+        Self {
+            words: words.into_iter().map(|m| Hidden::hide(m.clone())).collect::<Vec<_>>(),
```
Comment (sdbondi) [inline base_layer/key_manager/src/lib.rs]: Clone may create extra copies in memory, this should work if you take in a `Vec<String>` instead of `&[String]`
```suggestion
            words: words.into_iter().map(Hidden::hide).collect::<Vec<_>>(),
```

Comment (stringhandler) [reply base_layer/key_manager/src/lib.rs]: Agree. You could also zeroize the strings in the vec that you pass in

Comment (jorgeantonio21) [reply base_layer/key_manager/src/lib.rs]: Thanks for the suggestions, I refactored the input type to `Vec<Hidden<String>>`.

File: applications/tari_console_wallet/src/recovery.rs [hunk 2]
```diff
@@ -52,7 +53,8 @@ pub fn prompt_private_key_from_seed_words() -> Result<CipherSeed, ExitError> {
         println!();
         println!("Type or paste all of your seed words on one line, only separated by spaces.");
         let input = rl.readline(">> ").map_err(|e| ExitError::new(ExitCode::IOError, e))?;
-        let seed_words: Vec<String> = input.split_whitespace().map(str::to_string).collect();
+        let seed_words: SeedWords =
```
Comment (sdbondi) [inline applications/tari_console_wallet/src/recovery.rs:57]: TODO: fix leaks

File: applications/tari_console_wallet/src/lib.rs [hunk 3]
```diff
@@ -213,13 +214,14 @@ fn get_password(config: &ApplicationConfig, cli: &Cli) -> Option<SafePassword> {
...
         let seed = if cli.seed_words.is_some() {
-            let seed_words: Vec<String> = cli
-                .seed_words
-                .clone()
-                .unwrap()
-                .split_whitespace()
-                .map(|v| v.to_string())
-                .collect();
+            let seed_words: SeedWords = SeedWords::new(
+                cli.seed_words
```
Comment (sdbondi) [inline applications/tari_console_wallet/src/lib.rs:219]: TODO: fix leaks

**Review by sdbondi — DISMISSED** [review]
Awesome

The cli and seed work prompt still leak but these can be fixed in another PR(s) as both of them require a little refactoring

File: applications/tari_console_wallet/src/recovery.rs (hunk 2 above)
Comment (jorgeantonio21) [reply applications/tari_console_wallet/src/recovery.rs:57]: Will add the comments, thanks !

File: applications/tari_console_wallet/src/lib.rs (hunk 3 above)
Comment (jorgeantonio21) [reply applications/tari_console_wallet/src/lib.rs:219]: Will add the comments, thanks !

File: applications/tari_console_wallet/src/recovery.rs (hunk 2 above)
Comment (jorgeantonio21) [reply applications/tari_console_wallet/src/recovery.rs:57]: Refactored to zeroize input

File: applications/tari_console_wallet/src/lib.rs [hunk 4]
```diff
@@ -213,13 +215,16 @@ fn get_password(config: &ApplicationConfig, cli: &Cli) -> Option<SafePassword> {
...
+            // need to zeroize first, to clean up memory of cli.seed_words clone
+            let vec_words = Zeroizing::new(cli.seed_words.clone());
+            let seed_words: SeedWords = SeedWords::new(
+                vec_words
+                    .as_ref()
+                    .unwrap()
+                    .split_whitespace()
+                    .map(|v| Hidden::hide(v.to_string()))
+                    .collect(),
+            );
```
Comment (sdbondi) [inline applications/tari_console_wallet/src/lib.rs]: You could just move each string into the Hidden.
```suggestion
            let seed_words: SeedWords = SeedWords::new(
                cli.seed_words.clone()
                    .unwrap()
                    .split_whitespace()
                    .map(Hidden::hide)
                    .collect(),
            );
```

Note that cli.seed_words still leaks

File: base_layer/key_manager/src/cipher_seed.rs [hunk 5]
```diff
@@ -271,7 +284,7 @@ impl CipherSeed {
             entropy.as_ref(),
             version,
             salt.as_ref(),
-            mac_key.as_ref(),
+            mac_key.reveal(),
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/cipher_seed.rs]:
```suggestion
            &mac_key,
```

File: base_layer/key_manager/src/cipher_seed.rs [hunk 6]
```diff
@@ -362,15 +375,23 @@ impl CipherSeed {
...
         let hasher = argon2::Argon2::new(argon2::Algorithm::Argon2d, argon2::Version::V0x13, params);
         hasher
-            .hash_password_into(passphrase.as_bytes(), argon2_salt, main_key.as_mut())
+            .hash_password_into(passphrase.reveal(), argon2_salt, main_key.reveal_mut())
             .map_err(|_| KeyManagerError::CryptographicError("Problem generating Argon2 password hash".to_string()))?;
 
         // Split off the keys
-        let encryption_key = Zeroizing::new(main_key.as_ref()[..CIPHER_SEED_ENCRYPTION_KEY_BYTES].to_vec());
-        let mac_key = Zeroizing::new(main_key.as_ref()[CIPHER_SEED_ENCRYPTION_KEY_BYTES..].to_vec());
+        let mut encryption_key = CipherSeedEncryptionKey::from([0u8; CIPHER_SEED_ENCRYPTION_KEY_BYTES]);
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/cipher_seed.rs]:
```suggestion
        let mut encryption_key = CipherSeedEncryptionKey::from(SafeArray::default());
```

File: base_layer/key_manager/src/cipher_seed.rs [hunk 7]
```diff
@@ -362,15 +375,23 @@ impl CipherSeed {
...
+        encryption_key
+            .reveal_mut()
+            .copy_from_slice(&main_key.reveal()[..CIPHER_SEED_ENCRYPTION_KEY_BYTES]);
+
+        let mut mac_key = CipherSeedMacKey::from([0u8; CIPHER_SEED_MAC_KEY_BYTES]);
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/cipher_seed.rs]:
```suggestion
        let mut mac_key = CipherSeedMacKey::from(SafeArray::default());
```

File: base_layer/key_manager/src/cipher_seed.rs [hunk 8]
```diff
@@ -176,7 +183,7 @@ impl CipherSeed {
             self.entropy.as_ref(),
             CIPHER_SEED_VERSION,
             self.salt.as_ref(),
-            mac_key.as_ref(),
+            mac_key.reveal(),
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/cipher_seed.rs]:
```suggestion
            &mac_key,
```

File: base_layer/key_manager/src/cipher_seed.rs [hunk 9]
```diff
@@ -188,7 +195,7 @@ impl CipherSeed {
         secret_data.extend(&mac);
 
         // Encrypt the secret data
-        Self::apply_stream_cipher(&mut secret_data, encryption_key.as_ref(), self.salt.as_ref())?;
+        Self::apply_stream_cipher(&mut secret_data, encryption_key.reveal(), self.salt.as_ref())?;
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/cipher_seed.rs]:
```suggestion
        Self::apply_stream_cipher(&mut secret_data, &encryption_key, self.salt.as_ref())?;
```

File: base_layer/key_manager/src/cipher_seed.rs [hunk 10]
```diff
@@ -251,7 +264,7 @@ impl CipherSeed {
 
         // Decrypt the secret data: birthday, entropy, MAC
         let mut secret_data = Zeroizing::new(encrypted_seed.split_off(1));
-        Self::apply_stream_cipher(&mut secret_data, encryption_key.as_ref(), salt.as_ref())?;
+        Self::apply_stream_cipher(&mut secret_data, encryption_key.reveal(), salt.as_ref())?;
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/cipher_seed.rs]:
```suggestion
        Self::apply_stream_cipher(&mut secret_data, &encryption_key, salt.as_ref())?;
```

File: base_layer/key_manager/src/cipher_seed.rs [hunk 11]
```diff
@@ -34,12 +34,16 @@ use rand::{rngs::OsRng, RngCore};
 use serde::{Deserialize, Serialize};
 use subtle::ConstantTimeEq;
 use tari_crypto::hash::blake2::Blake256;
+use tari_utilities::{hidden::Hidden, SafePassword};
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/cipher_seed.rs]:
```suggestion
use tari_utilities::{hidden::Hidden, SafePassword, safe_array::SafeArray};
```

File: base_layer/key_manager/src/cipher_seed.rs (hunk 6 above)
Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: This lets you take advantage of `SafeArray` benefits, including the default constructor.

File: base_layer/key_manager/src/cipher_seed.rs (hunk 7 above)
Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: This lets you take advantage of `SafeArray` benefits, including the default constructor.

File: base_layer/key_manager/src/cipher_seed.rs (hunk 8 above)
Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: Recommend you update the signature of `generate_mac` to take a `&CipherSeedMacKey` instead of `&[u8]`, and then have `generate_mac` call `reveal` itself when needed. This helps avoid passing in the wrong key type, and is a key (pun intended) benefit of `Hidden` type differentiation.

File: base_layer/key_manager/src/cipher_seed.rs (hunk 5 above)
Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: Recommend you update the signature of `generate_mac` to take a `&CipherSeedMacKey` instead of `&[u8]`, and then have `generate_mac` call `reveal` itself when needed. This helps avoid passing in the wrong key type, and is a key (pun intended) benefit of `Hidden` type differentiation.

File: base_layer/key_manager/src/cipher_seed.rs (hunk 9 above)
Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: Recommend you update the signature of `apply_stream_cipher` to take a `&CipherSeedEncryptionKey` instead of `&[u8]`, and then have `apply_stream_cipher` call `reveal` itself when needed. This helps avoid passing in the wrong key type, and is a key (pun intended) benefit of `Hidden` type differentiation.

File: base_layer/key_manager/src/cipher_seed.rs (hunk 10 above)
Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: Recommend you update the signature of `apply_stream_cipher` to take a `&CipherSeedEncryptionKey` instead of `&[u8]`, and then have `apply_stream_cipher` call `reveal` itself when needed. This helps avoid passing in the wrong key type, and is a key (pun intended) benefit of `Hidden` type differentiation.

File: base_layer/key_manager/src/key_manager.rs [hunk 12]
```diff
@@ -30,21 +30,22 @@ use tari_crypto::{
...
+use zeroize::Zeroize;
 
 use crate::{cipher_seed::CipherSeed, mac_domain_hasher, LABEL_DERIVE_KEY};
 
-#[derive(Clone, Derivative, Serialize, Deserialize)]
+#[derive(Clone, Derivative, Serialize, Deserialize, Zeroize)]
 #[derivative(Debug)]
 pub struct DerivedKey<K>
-where K: SecretKey
+where K: SecretKey + Zeroize
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/key_manager.rs]:
```suggestion
where K: SecretKey
```

Comment (AaronFeickert) [reply base_layer/key_manager/src/key_manager.rs]: Not needed, since `SecretKey` now implements `Zeroize`.

File: base_layer/key_manager/src/key_manager.rs [hunk 13]
```diff
@@ -58,7 +59,7 @@ pub struct KeyManager<K: SecretKey, D: Digest + LengthExtensionAttackResistant>
 
 impl<K, D> KeyManager<K, D>
 where
-    K: SecretKey,
+    K: SecretKey + Zeroize,
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/key_manager.rs]:
```suggestion
    K: SecretKey,
```

Comment (AaronFeickert) [reply base_layer/key_manager/src/key_manager.rs]: Not needed, since `SecretKey` now implements `Zeroize`.

File: base_layer/key_manager/src/key_manager.rs [hunk 14]
```diff
@@ -124,7 +125,7 @@ where
 
 impl<K, D> Default for KeyManager<K, D>
 where
-    K: SecretKey,
+    K: SecretKey + Zeroize,
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/key_manager.rs]:
```suggestion
    K: SecretKey,
```

Comment (AaronFeickert) [reply base_layer/key_manager/src/key_manager.rs]: Not needed, since `SecretKey` now implements `Zeroize`.

File: base_layer/key_manager/src/lib.rs [hunk 15]
```diff
@@ -32,10 +39,192 @@ pub(crate) fn mac_domain_hasher<D: Digest + LengthExtensionAttackResistant>(
     DomainSeparatedHasher::<D, KeyManagerDomain>::new_with_label(label)
 }
 
+hidden_type!(CipherSeedEncryptionKey, [u8; CIPHER_SEED_ENCRYPTION_KEY_BYTES]);
+hidden_type!(CipherSeedMacKey, [u8; CIPHER_SEED_MAC_KEY_BYTES]);
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/lib.rs]:
```suggestion
hidden_type!(CipherSeedEncryptionKey, SafeArray<u8, CIPHER_SEED_ENCRYPTION_KEY_BYTES>);
hidden_type!(CipherSeedMacKey, SafeArray<u8, CIPHER_SEED_MAC_KEY_BYTES>);
```

Comment (AaronFeickert) [reply base_layer/key_manager/src/lib.rs]: Might as well take advantage of the new `SafeArray` benefits here.

File: base_layer/key_manager/src/lib.rs [hunk 16]
```diff
@@ -7,6 +7,13 @@ use tari_crypto::{
     hash_domain,
     hashing::{DomainSeparatedHasher, LengthExtensionAttackResistant},
 };
+use tari_utilities::{hidden::Hidden, hidden_type};
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/lib.rs]:
```suggestion
use tari_utilities::{hidden::Hidden, hidden_type, safe_array::SafeArray};
```

File: base_layer/key_manager/src/mnemonic.rs [hunk 17]
```diff
@@ -100,7 +105,8 @@ impl MnemonicLanguage {
                 return Err(MnemonicError::UnknownLanguage);
             },
             Ordering::Greater => {
-                for word in words {
+                for word_ind in 0..words.len() {
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/mnemonic.rs:108]: Is it worth it to have `SeedWords` implement an iterator that provides word references? Then you don't need to mess around with indexes.

File: base_layer/key_manager/src/mnemonic.rs [hunk 18]
```diff
@@ -112,7 +118,8 @@ impl MnemonicLanguage {
                     // yielded from the initial word for this iteration
                     for language in languages {
                         let mut consistent = true;
-                        for compare in words {
+                        for compare_ind in 0..words.len() {
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/mnemonic.rs:121]: Is it worth it to have `SeedWords` implement an iterator that provides word references? Then you don't need to mess around with indexes.

File: base_layer/key_manager/src/mnemonic.rs [hunk 19]
```diff
@@ -171,7 +186,7 @@ fn find_mnemonic_word_from_index(index: usize, language: MnemonicLanguage) -> Re
 }
 
 /// Converts a vector of bytes to a sequence of mnemonic words using the specified language
-pub fn from_bytes(bytes: &[u8], language: MnemonicLanguage) -> Result<Vec<String>, MnemonicError> {
+pub fn from_bytes(bytes: &[u8], language: MnemonicLanguage) -> Result<SeedWords, MnemonicError> {
     let mut bits = bytes_to_bits(bytes);
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/mnemonic.rs]: Shouldn't `bits` be considered sensitive data?

File: base_layer/key_manager/src/mnemonic.rs [hunk 20]
```diff
@@ -184,22 +199,22 @@ pub fn from_bytes(bytes: &[u8], language: MnemonicLanguage) -> Result<Vec<String
...
     }
 
-    Ok(mnemonic_sequence)
+    Ok(SeedWords::new(mnemonic_sequence))
 }
 
 /// Generates a vector of bytes that represent the provided mnemonic sequence of words, the language of the mnemonic
 /// sequence is detected
-pub fn to_bytes(mnemonic_seq: &[String]) -> Result<Vec<u8>, MnemonicError> {
+pub fn to_bytes(mnemonic_seq: &SeedWords) -> Result<Vec<u8>, MnemonicError> {
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/mnemonic.rs]: Is the return `Vec<u8>` sensitive data?

File: base_layer/key_manager/src/mnemonic.rs [hunk 21]
```diff
@@ -219,14 +234,19 @@ pub fn to_bytes(mnemonic_seq: &[String]) -> Result<Vec<u8>, MnemonicError> {
...
+pub fn to_bytes_with_language(mnemonic_seq: &SeedWords, language: &MnemonicLanguage) -> Result<Vec<u8>, MnemonicError> {
     const MASK: u64 = (1u64 << 8) - 1;
     let mut bytes = Vec::new();
     let mut rest = 0u64;
     let mut rest_bits: u8 = 0;
 
-    for curr_word in mnemonic_seq {
-        let index = find_mnemonic_index_from_word(curr_word, *language)? as u64;
+    for curr_ind in 0..mnemonic_seq.len() {
+        let index = find_mnemonic_index_from_word(
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/mnemonic.rs:246]: Is this sensitive data?

**Review by AaronFeickert — CHANGES_REQUESTED** [review]

File: base_layer/key_manager/src/cipher_seed.rs (hunk 5 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/cipher_seed.rs]: Agreed ! Refactor done !

File: base_layer/key_manager/src/cipher_seed.rs (hunk 7 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/cipher_seed.rs]: Resolved !

File: base_layer/key_manager/src/cipher_seed.rs (hunk 8 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/cipher_seed.rs]: Great ! Refactored

File: base_layer/key_manager/src/cipher_seed.rs (hunk 9 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/cipher_seed.rs]: Definitely ! Thanks for the suggestion !

File: base_layer/key_manager/src/cipher_seed.rs (hunk 10 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/cipher_seed.rs]: Resolved !

File: base_layer/key_manager/src/key_manager.rs (hunk 12 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/key_manager.rs]: Nice catch, it remained from one of our previous conversations on the subject !

File: base_layer/key_manager/src/key_manager.rs (hunk 13 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/key_manager.rs]: Definitely ! Thanks for the catch !

File: base_layer/key_manager/src/lib.rs (hunk 15 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/lib.rs]: Refactored accordingly !

File: base_layer/key_manager/src/mnemonic.rs (hunk 17 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/mnemonic.rs:108]: I would say that it would be nice to have it. But honestly, to implement `Iterator` one needs to make some lifetime algebra, which adds unnecessary complexity to the `SeedWords` type. Since these are the only instances in which we need to traverse the `SeedWords` type, I think it might be not worth the extra complexity. But happy to refactor if you think otherwise :)

File: base_layer/key_manager/src/mnemonic.rs (hunk 18 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/mnemonic.rs:121]: See comment above.

File: base_layer/key_manager/src/mnemonic.rs (hunk 20 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/mnemonic.rs]: Yup, better to Hide it ! Nice catch !

File: base_layer/key_manager/src/mnemonic.rs (hunk 21 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/mnemonic.rs:246]: I wrap it with the `Hidden` type, even though these values live on the Stack. I wonder also if casting using `as` does a copy or not.

File: base_layer/key_manager/src/mnemonic.rs (hunk 19 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/mnemonic.rs]: They can be, definitely ! Nice catch

File: base_layer/key_manager/src/mnemonic.rs (hunk 21 above)
Comment (sdbondi) [reply base_layer/key_manager/src/mnemonic.rs:246]: I think `index` and the subsequent operations on it will occur in CPU registers so not concerned about that.
However, the resulting `Vec<u8>` is sensitive data

**Review by sdbondi — APPROVED** [review]

File: base_layer/key_manager/src/mnemonic.rs (hunk 21 above)
Comment (jorgeantonio21) [reply base_layer/key_manager/src/mnemonic.rs:246]: That's cool ! Less allocations as well :) thanks @sdbondi

**Review by stringhandler — APPROVED** [review]

File: base_layer/key_manager/src/mnemonic.rs (hunk 17 above)
Comment (AaronFeickert) [reply base_layer/key_manager/src/mnemonic.rs:108]: Ah, I hadn't considered that lifetimes would be problematic when writing this. As you say, it's probably not worth it for the two times when it would be used, and the bounds checks are correct as implemented anyway.
