### PR TITLE
Refactor peer manager/node identity + bug fix #959

### LINKED ISSUE #959: Sending a message to a public key that is not in the PeerManager peer list crashes the outbound message pipeline
To reproduce:
Send a message (like a transaction via the wallet) to a public_key that has not been added to the Peer Manager and you get the error shown below with some logs. 

The ```OutboundError(RequesterReplyChannelClosed)``` error seems to occur when the Reply Channel is dropped by the Outbound Message Service/Pipeline while the handle is waiting for its reply. This seems to imply some form of crash of that thread.

```
[2019-11-03T10:03:45Z INFO  tari_storage::lmdb_store::store] (/var/folders/yd/9_krd2dx0bscq8c3qtq4395c0000gn/T/qELpfnSJ.trPuZHQn3gkV/) LMDB environment created with a capacity of 10 MB.
[2019-11-03T10:03:45Z INFO  tari_comms::control_service::worker] Control service starting on 127.0.0.1:22123...
[2019-11-03T10:03:45Z INFO  tari_comms::inbound_message_service::inbound_message_service] Inbound Message Pipeline started
[2019-11-03T10:03:45Z INFO  tari_wallet::output_manager_service::service] Output Manager Service started
[2019-11-03T10:03:45Z INFO  tari_wallet::contacts_service::service] Contacts Service started
[2019-11-03T10:03:46Z ERROR tari_comms_middleware::pipeline] ServicePipeline error: PeerManagerError(PeerNotFoundError)
test wallet::test_data_generation ... FAILED

failures:

---- wallet::test_data_generation stdout ----
thread 'wallet::test_data_generation' panicked at 'Could not send test transaction: OutboundError(RequesterReplyChannelClosed)', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### PR DESCRIPTION
**Pull request by sdbondi**
## Description

- When a peer is not found using the Direct broadcast strategy, the
  outbound requester will now return `0` instead of a channel closed
  error (Fixes #959)
- Removed redundant `PeerNodeIdentity`
- Consistent usage of `NodeIdentity` (private fields, use getters only)

## Motivation and Context

Closes #959 

## How Has This Been Tested?

Existing tests updated

## Types of changes

* [x] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [x] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [x] I'm merging against the `development` branch
* [x] I ran `cargo-fmt --all` before pushing
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.

### CODE REVIEW

File: base_layer/wallet/tests/transaction_service/mod.rs [hunk 1]
```diff
@@ -221,21 +221,13 @@ fn manage_single_transaction() {
...
 
     runtime.block_on(alice_oms.add_output(uo1)).unwrap();
 
     runtime
-        .block_on(alice_ts.send_transaction(
-            bob_node_identity.identity.public_key.clone(),
-            value,
-            MicroTari::from(20),
-        ))
+        .block_on(alice_ts.send_transaction(bob_node_identity.public_key().clone(), value, MicroTari::from(20)))
```
Comment (CjS77) [inline base_layer/wallet/tests/transaction_service/mod.rs]: Did you know you can write this as `20*uT`?
