### PR TITLE
fix: peer_db null update where none should be written as null

### LINKED ISSUE #7469: Seedstrap is failing
Peer manager does not seem to be able to get seed peers:
```
2025-09-03 13:35:24.875635000 [p2p::initialization] [Thread:252521] DEBUG Adding seed peer [PeerFlags(SEED)[ab2fad12f4486284] PK=4cdfb70e0b38b60c6a3573b2870e32bc3d846419c606ea379f43650b80f38409 (/ip4/51.83.4.85/tcp/18189) - . Type: BASE_NODE. User agent: <unknown>.] // base_layer/p2p/src/initialization.rs:413
2025-09-03 13:35:24.878015000 [p2p::initialization] [Thread:252521] DEBUG Adding seed peer [PeerFlags(SEED)[ace05844c9c9723a] PK=1e08628960f75b7e324f010b2ee609a9e28097e9101f4d769d474a38b6ee2d76 (/ip4/51.83.102.25/tcp/18189) - . Type: BASE_NODE. User agent: <unknown>.] // base_layer/p2p/src/initialization.rs:413
2025-09-03 13:35:24.878549000 [p2p::initialization] [Thread:252521] DEBUG Adding seed peer [PeerFlags(SEED)[ace05844c9c9723a] PK=1e08628960f75b7e324f010b2ee609a9e28097e9101f4d769d474a38b6ee2d76 (/ip6/2001:41d0:303:a619::1/tcp/18189) - . Type: BASE_NODE. User agent: <unknown>.] // base_layer/p2p/src/initialization.rs:413
2025-09-03 13:35:24.879499000 [p2p::initialization] [Thread:252521] DEBUG Adding seed peer [PeerFlags(SEED)[ab2fad12f4486284] PK=4cdfb70e0b38b60c6a3573b2870e32bc3d846419c606ea379f43650b80f38409 (/ip6/2001:41d0:303:9a55::1/tcp/18189) - . Type: BASE_NODE. User agent: <unknown>.] // base_layer/p2p/src/initialization.rs:413
2025-09-03 13:35:24.879781000 [p2p::initialization] [Thread:252521] DEBUG Adding seed peer [PeerFlags(SEED)[ace05844c9c9723a] PK=1e08628960f75b7e324f010b2ee609a9e28097e9101f4d769d474a38b6ee2d76 (/onion3/tadnxyokalnqjtvu6mlhxndcq4v2tlolotpvrflscdmi7lcautao3had:18141) - . Type: BASE_NODE. User agent: <unknown>.] // base_layer/p2p/src/initialization.rs:413
2025-09-03 13:35:24.879995000 [p2p::initialization] [Thread:252521] DEBUG Adding seed peer [PeerFlags(SEED)[ab2fad12f4486284] PK=4cdfb70e0b38b60c6a3573b2870e32bc3d846419c606ea379f43650b80f38409 (/onion3/mhfptgpcj6htjkr5zwurom32wvt7x76ovqzn2ttnwo2bnku6baeaaiyd:18141) - . Type: BASE_NODE. User agent: <unknown>.] // base_layer/p2p/src/initialization.rs:413
2025-09-03 13:35:24.880303000 [p2p::initialization] [Thread:252521] DEBUG Adding seed peer [PeerFlags(SEED)[ace05844c9c9723a] PK=1e08628960f75b7e324f010b2ee609a9e28097e9101f4d769d474a38b6ee2d76 (/ip4/51.83.102.25/tcp/18189) - . Type: BASE_NODE. User agent: <unknown>.] // base_layer/p2p/src/initialization.rs:413
WARN  Failed to get seed peers from PeerManager, using empty list // comms/core/src/connectivity/manager.rs:207
```
This happens from: 
https://github.com/tari-project/tari/pull/7396

Seed strap does not seem to be able to find any peers from the seed nodes:
```
13:17 WARN  SeedStrap: Failed to contact any seed nodes or retrieve new peers.
13:17 WARN  SeedStrap round was not successful. Waiting before next attempt.
```
This happens from: https://github.com/tari-project/tari/pull/7303

### PR DESCRIPTION
**Pull request by hansieodendaal**
Description
---
Fixed peer_db update where a `value = None` was ignored in the update set instead of changing the value to `null` in the database. This caused higher-level logic that depended on `null` to represent something to fail.

Fixes #7469.

Motivation and Context
---
See above.

This data extract shows data for `last_failed_reason` where it should have been cleared, because `last_seen` has been updated recently (active connections).

node_id | address | last_seen | last_failed_reason
-- | -- | -- | --
ed1cc6f6b4fdd0cb71cf1c06b8 | /onion3/xvca7s6ls5jy2e2yblofve5l5oukgvf4c5lbt6ls3a7ksezjl4rhfmyd:18141 | 2025/09/10   14:38:17 | Dial   timeout dialing   /onion3/xvca7s6ls5jy2e2yblofve5l5oukgvf4c5lbt6ls3a7ksezjl4rhfmyd:18141 after   60.00s
ab2fad12f448628436bcbe98d1 | /ip4/51.83.4.85/tcp/18189 | 2025/09/10   14:49:17 | Transport   error for /ip4/51.83.4.85/tcp/18189: An attempt was made to access a socket   in a way forbidden by its access permissions. (os error 10013)
5090e6ee18fd7353462b3dadcd | /onion3/i5drghe3xlbcrpi2ejgifxrlfvddqikwiqrbuur6kzb5fdx6ufisvtid:18141 | 2025/09/10   14:49:17 | Dial   timeout dialing   /onion3/i5drghe3xlbcrpi2ejgifxrlfvddqikwiqrbuur6kzb5fdx6ufisvtid:18141 after   60.00s

How Has This Been Tested?
---
Added a unit test to confirm updates are working as expected.
System-level testing on esmeralda, where this is most apparent.

What process can a PR reviewer use to test or verify this change?
---
Code review.
System-level testing on esmeralda.

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

## Summary by CodeRabbit

- Bug Fixes
  - Clearing banned/failed reasons now persists correctly when updating peer/address activity.

- Refactor
  - Database schema tightened: several fields made non-null and timestamp handling standardized.
  - Address statistics now use consistent numeric types and source storage.
  - Added/adjusted indexes to improve peer and address lookup performance.

- Chores
  - Added reversible migration to apply and revert the schema changes across environments.

- Tests
  - New coverage validating NULL clearing and persistence behavior.

### CODE REVIEW

File: comms/core/src/peer_manager/storage/database.rs [hunk 1]
```diff
@@ -1710,12 +1709,13 @@ pub struct NewPeerSql {
...
+#[diesel(treat_none_as_null = true)]
 pub struct UpdatePeerSql {
     pub node_id: String,
     pub banned_until: Option<chrono::NaiveDateTime>,
     pub banned_reason: Option<String>,
-    pub supported_protocols: Option<String>,
-    pub user_agent: Option<String>,
+    pub supported_protocols: String,
+    pub user_agent: String,
     pub metadata: Option<Vec<u8>>,
```
Comment (SWvheerden) [inline comms/core/src/peer_manager/storage/database.rs]: and this field?

**Review by SWvheerden — CHANGES_REQUESTED** [review]
You have set this: `#[diesel(treat_none_as_null = true)]`
but a lot of the fields remains options, and it feels like they should not be deleted

File: comms/core/src/peer_manager/storage/database.rs (hunk 1 above)
Comment (hansieodendaal) [reply comms/core/src/peer_manager/storage/database.rs]: All these fields are set/contolled from the peer to be added or updated - if something is cleared (set to None) on the peer data it should be cleared here as well. In the update sql for peers and multi_addresses tables all the fields are assigned - so whatever they are is applied, nothing will be cleared by chance.

The metadata field is assigned as
```rust
pub fn serialize_metadata(metadata: &HashMap<u8, Vec<u8>>) -> Result<Option<Vec<u8>>, StorageError> {
    if metadata.is_empty() {
        Ok(None)
    } else {
        Ok(Some(serde_json::to_vec(metadata)?))
    }
}
```
so it will only be cleared if it is cleared on the incoming peer, and currently it is never cleared from the application layer.

**Review by SWvheerden — APPROVED** [review]

File: comms/core/src/peer_manager/storage/database.rs [hunk 2]
```diff
@@ -689,19 +665,21 @@ impl PeerDatabaseSql {
...
-            .execute(conn)?;
+        diesel::update(
+            peers::table.filter(peers::node_id.eq(update_peer_sql.peer.node_id.clone().unwrap_or_default())),
+        )
+        .set(&update_peer_sql.peer)
+        .execute(conn)?;
         let peer_id = peers::table
-            .filter(peers::node_id.eq(update_peer_sql.peer.node_id.clone()))
+            .filter(peers::node_id.eq(update_peer_sql.peer.node_id.clone().unwrap_or_default()))
             .select(peers::peer_id)
```
[the remark this answers is not in the document]
Comment (MCozhusheck) [reply comms/core/src/peer_manager/storage/database.rs:675]: I agree with code rabbit here. 
```rust
diesel::update(
            peers::table.filter(peers::node_id.eq(update_peer_sql.peer.node_id.clone().unwrap_or_default())),
        )
```
I think it's more preferable to fail whole update than to update whatever the default of `node_id` is.

File: comms/core/src/peer_manager/storage/database.rs [hunk 3]
```diff
@@ -689,19 +665,21 @@ impl PeerDatabaseSql {
...
             .first::<i64>(conn)?;
 
         // Update the associated multi-addresses
         for address_update in update_peer_sql.addresses {
             let updated = diesel::update(
                 multi_addresses::table
-                    .filter(multi_addresses::address.eq(address_update.address.clone()))
+                    .filter(multi_addresses::address.eq(address_update.address.clone().unwrap_or_default()))
```
Comment (MCozhusheck) [inline comms/core/src/peer_manager/storage/database.rs:682]: same case here.

File: comms/core/src/peer_manager/storage/database.rs [hunk 4]
```diff
@@ -1825,17 +1803,17 @@
 impl From<&MultiaddrWithStats> for UpdateMultiaddrWithStatsSql {
     fn from(address: &MultiaddrWithStats) -> Self {
         UpdateMultiaddrWithStatsSql {
-            address: address.to_string(),
-            is_external: address.is_external(),
-            last_seen: address.last_seen(),
+            address: Some(address.to_string()),
```
[the remark this answers is not in the document]
Comment (MCozhusheck) [reply comms/core/src/peer_manager/storage/database.rs:1806]:
```rust
    pub fn address(&self) -> &Multiaddr {
        &self.address
    }
```
From the implementation of `MultiaddrWithStats`

Isn't that the same thing?
