### PR TITLE
fix(console_wallet): use cli.non_interactive instead of prompt to show seed words

### LINKED ISSUE #4568: console-wallet: seed words don't show up if using the --password flag
When starting a new console wallet with `--password 'xxx'` the seed words do not show

### PR DESCRIPTION
**Pull request by willyrgf**
Description
---

When starting a new console wallet with --password 'xxx' the seed words do not show. 

It's happen because of the property used to decide show or not the seed words its based on prompt instead of --non-interactive arg.

More detailed here: https://github.com/tari-project/tari/issues/4568

---

Closes https://github.com/tari-project/tari/issues/4568

### CODE REVIEW

**Comment by stringhandler** [comment]
Looks good. Will test it locally

File: applications/tari_console_wallet/src/main.rs [hunk 1]
```diff
@@ -219,6 +221,13 @@ fn main_inner() -> Result<(), ExitError> {
     result
 }
 
+fn get_password(config: &ApplicationConfig, cli: &Cli) -> Option<SafePassword> {
+    cli.password
+        .as_ref()
+        .or(config.wallet.password.as_ref())
```
Comment (jorgeantonio21) [inline applications/tari_console_wallet/src/main.rs:227]: The logic was already in the code previously. But is it safe in case the user doesn't provide `passwor` via the cli, we are getting it from the `config.wallet` ?

Comment (jorgeantonio21) [reply applications/tari_console_wallet/src/main.rs:227]: Previously, this logic was placed within `fn main_inner()`, file `applications/tari_console_wallet/stc/main.rs`. It might be potentially risky to use this function outside that given context.

**Review by sdbondi — APPROVED** [review]
Tested and works - thanks!

File: applications/tari_console_wallet/src/main.rs (hunk 1 above)
Comment (sdbondi) [reply applications/tari_console_wallet/src/main.rs:227]: Looks ok to me - not sure exactly what the concern is but since the password bytes aren't moved around the stack (only the pointer Box<[u8]> is, not the contents of the pointer), and the function is private I don't think there is any additional risk. Feel free to reopen if you disagree :)

Comment (jorgeantonio21) [reply applications/tari_console_wallet/src/main.rs:227]: Perfect, thanks for the explanation @sdbondi ! :)
