### PR TITLE
fix!: refactor `CipherSeed`, zeroize, and fix key derivation

### LINKED ISSUE #4859: Cipher seed MAC key is derived incorrectly
To generate an encrypted `CipherSeed`, a user-supplied passphrase is used to produce a 64-byte main key. This key is intended to be split into two keys: a 32-byte MAC key, and a 32-byte encryption key. This is implemented incorrectly, such that the last 32 bytes of the main key are [used as the MAC key](https://github.com/tari-project/tari/blob/5b0eb0459c7d29a25339c22a289153d27d57388e/base_layer/key_manager/src/cipher_seed.rs#L320-L332) instead of the first 32 bytes. This means the MAC and encryption keys are identical, which is dangerous in general.

Since the password key derivation function is already run twice, one fix is to run it (using 32-byte output) with a different salt for both keys, by appending a different byte flag to the original salt for each derived key. Another option is to run the key derivation function only once, and parse both derived keys at the same time; however, this might make proper zeroization more challenging (see below).

While we're at it, MAC verification should be done in constant time.

This is also a good opportunity to address the overarching topic in [issue 4846](https://github.com/tari-project/tari/issues/4846) and ensure that secret data produced or handled during `CipherSeed` processing is properly zeroized. While the `CipherSeed` struct itself zeroizes on drop, there are several other locations where passphrase, entropy, or other key data are not.

### PR DESCRIPTION
**Pull request by AaronFeickert**
Description
---
Significantly refactors `CipherSeed` for clarity, zeroizes internal secrets, fixes key derivation, and verifies MACs in constant time. Does _not_ zeroize external passphrases, which should be done separately. Fixes [issue 4859](https://github.com/tari-project/tari/issues/4859).

Motivation and Context
---
As noted in [issue 4859](https://github.com/tari-project/tari/issues/4859), `CipherSeed` MAC keys are derived incorrectly; in fact, the same main key is derived twice to obtain the MAC key and encryption key used for `CipherSeed` encryption. This work refactors for several goals:
- The password is only hashed a single time, so MAC and encryption keys are produced at the same time. This makes it easier to identify that they are being derived correctly, which they now are.
- Internal secrets are zeroized. Notably, passphrases from callers are _not_ yet zeroized, which should be done in subsequent work.
- MACs are verified in constant time using `subtle` functionality.
- The code is much clearer, making it easier to identify secret and non-secret data for review.

How Has This Been Tested?
---
Existing tests, as the external API does not change. Manual inspection that keys are now derived correctly.

BREAKING CHANGE: Existing (version 0) seeds no longer work. Only version 1 seeds are valid.

### CODE REVIEW

File: base_layer/key_manager/src/cipher_seed.rs [hunk 1]
```diff
@@ -141,10 +140,11 @@ impl CipherSeed {
         CipherSeed::new_with_birthday(birthday)
     }
 
+    /// Generate a new seed with a given birthday
     fn new_with_birthday(birthday: u16) -> Self {
-        let mut entropy = [0u8; CIPHER_SEED_ENTROPY_BYTES];
-        OsRng.fill_bytes(&mut entropy);
-        let mut salt = [0u8; CIPHER_SEED_SALT_BYTES];
+        let mut entropy = vec![0u8; CIPHER_SEED_ENTROPY_BYTES];
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/cipher_seed.rs]: Does this need a `Zeroizing` wrapper since it's a vector and the eventual initialized `CipherSeed` struct zeroizes on drop?

File: base_layer/key_manager/src/cipher_seed.rs [hunk 2]
```diff
@@ -155,223 +155,205 @@ impl CipherSeed {
...
-        let salt_bytes = salt_vec.into_inner().map_err(|_| KeyManagerError::InvalidData)?;
-
         Ok(Self {
-            version: received_version,
-            birthday: decrypted_birthday,
-            entropy: decrypted_entropy,
-            salt: salt_bytes,
+            version,
+            birthday,
+            entropy: (*entropy).clone(),
```
Comment (AaronFeickert) [inline base_layer/key_manager/src/cipher_seed.rs]: See other comment. Same question.

File: base_layer/key_manager/src/cipher_seed.rs (hunk 1 above)
Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: If so, it would need to be dereferenced and cloned (see other comment).

Comment (sdbondi) [reply base_layer/key_manager/src/cipher_seed.rs]: Zeroizing here is not needed, the vector (pointer + length) will be moved into the CipherSeed struct, and the same underlying buffer is zeroized on drop.

```rust
    #[test]
    fn zerioze() {
        let mut seed = CipherSeed::new();
        unsafe {
            let ptr = seed.entropy.as_ptr();
            seed.zeroize();
            for i in 0..(CIPHER_SEED_ENTROPY_BYTES as isize) {
                assert_eq!(*(ptr.offset(i)), 0, "not zero at index {}", i);
            }
        }
    }
```

File: base_layer/key_manager/src/cipher_seed.rs [hunk 3]
```diff
@@ -155,223 +155,205 @@ impl CipherSeed {
...
-
-        let calculated_checksum = crc_hasher.finalize();
-
-        let mut checksum_bytes: [u8; 4] = [0u8; 4];
-        checksum_bytes.copy_from_slice(&checksum_vec[..4]);
-        let checksum = u32::from_le_bytes(checksum_bytes);
-
-        if calculated_checksum != checksum {
+        crc_hasher.update(encrypted_seed.as_slice());
+        let expected_checksum = crc_hasher.finalize().to_le_bytes().to_vec();
```
Comment (sdbondi) [inline base_layer/key_manager/src/cipher_seed.rs]: nit: Allocation not necessary for byte comparison
```suggestion
        let expected_checksum = crc_hasher.finalize().to_le_bytes();
```

File: base_layer/key_manager/src/cipher_seed.rs (hunk 2 above)
Comment (sdbondi) [reply base_layer/key_manager/src/cipher_seed.rs]: This is all good because of `CipherSeed` zeroize.
If you wanted to save a clone you could 

```rust
let entropy = secret_data.split_off(CIPHER_SEED_BIRTHDAY_BYTES);
// ...
  // Verify the MAC in constant time to avoid leaking data
        if mac.ct_eq(&expected_mac).unwrap_u8() == 0 {
            let _drop = Zeroizing::new(entropy);
            return Err(KeyManagerError::DecryptionFailed);
        }

 Ok(Self {
            version,
            birthday,
            entropy,
            salt,
        })
```
but completely optional, and means we have to be more careful about early function exits.

File: base_layer/key_manager/src/cipher_seed.rs [hunk 4]
```diff
@@ -155,223 +155,205 @@ impl CipherSeed {
...
 
-        let mut final_seed = vec![CIPHER_SEED_VERSION];
-        final_seed.append(&mut plaintext.to_vec());
-        final_seed.append(&mut self.salt.to_vec());
+        // Assemble the final seed: version, main salt, secret data, checksum
+        let mut encrypted_seed =
+            Vec::<u8>::with_capacity(1 + CIPHER_SEED_MAIN_SALT_BYTES + secret_data.len() + CIPHER_SEED_CHECKSUM_BYTES);
+        encrypted_seed.push(CIPHER_SEED_VERSION);
+        encrypted_seed.append(&mut secret_data.to_vec());
+        encrypted_seed.append(&mut self.salt.to_vec());
```
Comment (sdbondi) [inline base_layer/key_manager/src/cipher_seed.rs]: nit: allocations
```suggestion
        encrypted_seed.extend(&self.salt);
```

File: base_layer/key_manager/src/cipher_seed.rs [hunk 5]
```diff
@@ -155,223 +155,205 @@ impl CipherSeed {
...
+        Self::apply_stream_cipher(&mut secret_data, encryption_key.as_ref(), &self.salt)?;
 
-        let mut final_seed = vec![CIPHER_SEED_VERSION];
-        final_seed.append(&mut plaintext.to_vec());
-        final_seed.append(&mut self.salt.to_vec());
+        // Assemble the final seed: version, main salt, secret data, checksum
+        let mut encrypted_seed =
+            Vec::<u8>::with_capacity(1 + CIPHER_SEED_MAIN_SALT_BYTES + secret_data.len() + CIPHER_SEED_CHECKSUM_BYTES);
+        encrypted_seed.push(CIPHER_SEED_VERSION);
+        encrypted_seed.append(&mut secret_data.to_vec());
```
Comment (sdbondi) [inline base_layer/key_manager/src/cipher_seed.rs]: nit:
```suggestion
        encrypted_seed.append(&mut secret_data);
```

File: base_layer/key_manager/src/cipher_seed.rs [hunk 6]
```diff
@@ -155,223 +155,205 @@ impl CipherSeed {
...
+        encrypted_seed.append(&mut self.salt.to_vec());
 
         let mut crc_hasher = CrcHasher::new();
-        crc_hasher.update(final_seed.as_slice());
-        let checksum = crc_hasher.finalize();
-        final_seed.append(&mut checksum.to_le_bytes().to_vec());
-        Ok(final_seed)
+        crc_hasher.update(encrypted_seed.as_slice());
+        let mut checksum = crc_hasher.finalize().to_le_bytes().to_vec();
+        encrypted_seed.append(&mut checksum);
```
Comment (sdbondi) [inline base_layer/key_manager/src/cipher_seed.rs]: nit:allocations
```suggestion
        let  checksum = crc_hasher.finalize().to_le_bytes();
        encrypted_seed.extend(&checksum);
```

File: base_layer/key_manager/src/cipher_seed.rs [hunk 7]
```diff
@@ -155,223 +155,205 @@ impl CipherSeed {
...
+            mac_key.as_ref(),
         )?;
 
-        plaintext.append(&mut mac);
+        // Assemble the secret data to be encrypted: birthday, entropy, MAC
+        let mut secret_data = Zeroizing::new(Vec::<u8>::with_capacity(
+            CIPHER_SEED_BIRTHDAY_BYTES + CIPHER_SEED_ENTROPY_BYTES + CIPHER_SEED_MAC_BYTES,
+        ));
+        secret_data.append(&mut self.birthday.to_le_bytes().to_vec());
+        secret_data.append(&mut self.entropy.clone());
```
Comment (sdbondi) [inline base_layer/key_manager/src/cipher_seed.rs]: self.entropy.clone()  leaks (I believe the compiler won't optimise the clone out because cloned value is being mutated/emptied but not zeroed)
```suggestion
        secret_data.extend(&self.birthday.to_le_bytes());
        secret_data.extend(&self.entropy);
```

**Review by sdbondi — COMMENTED** [review]
LGTM - some minor comments

**Comment by hansieodendaal** [comment]
utACK

**Comment by stringhandler** [comment]
Nice. Please add a note on how existing seed phrases and wallets are affected

File: base_layer/key_manager/src/cipher_seed.rs (hunk 2 above)
Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: Good point about early exists. I'd much rather ensure that secret data is wrapped as early as possible so we don't have to worry about it.

**Comment by AaronFeickert** [comment]
> Nice. Please add a note on how existing seed phrases and wallets are affected

Done. If you wanted an interesting test of the versioning system, we could bump the `CipherSeed` version number. This would allow for immediate detection of incompatible seeds that can be reported as such. Otherwise, existing seeds will generically fail as manipulated. But that seems a bit much in this case.

File: base_layer/key_manager/src/cipher_seed.rs [hunk 8]
```diff
@@ -113,12 +116,13 @@ pub const CIPHER_SEED_MAC_BYTES: usize = 5;
 pub struct CipherSeed {
     version: u8,
     birthday: u16,
-    entropy: [u8; CIPHER_SEED_ENTROPY_BYTES],
-    salt: [u8; CIPHER_SEED_SALT_BYTES],
+    entropy: Vec<u8>,
```
Comment (jorgeantonio21) [inline base_layer/key_manager/src/cipher_seed.rs]: Why should we replace fixed size arrays to `Vec`'s, in this case ? I personally think it is expressive to know in advance the size of both `entropy` and `salt`.

**Comment by jorgeantonio21** [comment]
Very cool ! Thanks for the detailed explanations as well. 

utACK

File: base_layer/key_manager/src/cipher_seed.rs (hunk 8 above)
Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: Using a `Vec` made it easier to handle zeroizing of secret data (due to heap storage), and also should keep the structure more general in case of future updates, where data sizes could change based on version. I could easily imagine a future where all size constants are part of a version-dependent lookup.

Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: I'm certainly open to changing back to arrays for now, but it seems like this requires much more careful zeroizing wrappers to account for copies/moves, which seems like a footgun to avoid.

Comment (sdbondi) [reply base_layer/key_manager/src/cipher_seed.rs]: `Box<[u8; CIPHER_SEED_SALT_BYTES]>` is also an option as that allocates a fixed size array on the heap and you move a pointer (Box) around, not the data. But happy to keep it as a vec

Comment (jorgeantonio21) [reply base_layer/key_manager/src/cipher_seed.rs]: Thanks for the explanations @AaronFeickert. I would say that @sdbondi suggestion is the most explicit. I am also happy to use `Vec` here, it is probably not worth spending time on refactoring it it, as of now.

Comment (AaronFeickert) [reply base_layer/key_manager/src/cipher_seed.rs]: The refactoring was pretty straightforward, so I went ahead and switched from `Vec<u8>` to `Box<[u8]>` for clarity on sizes. For some reason `Zeroizing` didn't like `Box<[u8]>`, so there's one spot where we do `Zeroizing<[u8]>` and then create the `Box` later (this is in case of MAC failure, as @sdbondi pointed out elsewhere); it didn't complain when we `#[derive(Zeroize)]` on `Box<[u8]>` though, which is odd...

**Review by stringhandler — APPROVED** [review]
