### PR TITLE
fix: key manager

### LINKED ISSUE #7599: Fix key manager legacy wallet outputs spend
### Coin split

Image

### Normal spend

Image

### PR DESCRIPTION
**Pull request by hansieodendaal**
Description
---
A recent PR added a stateless key manager, but introduced breaking changes for existing wallets in that the funds could not be spent. This PR fixes spending for legacy wallets.

Fixes #7599.

Motivation and Context
---
#### Invald key

When trying to send a transaction that has legacy funds (birthday before this PR), we get this error:

image

#### Validation failed

- Fixing the error above, we have a further error:

```rust
2025-11-24 07:31:43.984701900 [tari::wallet::client::http] INFO  Transaction submitted successfully to Base 
  Node wallet service at http://127.0.0.1:19001/
2025-11-24 07:31:43.984776700 [wallet::transaction_service::protocols::broadcast_protocol] INFO  Transaction (TxId: 
  4353595468878569032) submission response from Base Node: TxSubmissionResponse { accepted: false, 
  rejection_reason: ValidationFailed, is_synced: true }
```
```rust
2025-11-24 07:31:43.984020600 [c::val::aggregate_body_internal_consistency_validator] TRACE Checking script 
  and script offset
2025-11-24 07:31:43.984167800 [c::mp::mempool_storage] INFO  Validation failed due to error: Validation error: 
  The transaction is invalid: Signature is invalid: Verifying script signature
```

How Has This Been Tested?
---
- Added unit test `async fn test_convert_legacy_managed_and_derived_key()`
- Performed system-level testing (send transaction with legacy wallet)

What process can a PR reviewer use to test or verify this change?
---
- Code review
- System-level testing

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

## Summary by CodeRabbit

* **Refactor**
  * Strengthened validation for key identifiers with additional in-place checks and recursive handling of nested legacy keys.

* **Tests**
  * Added and updated tests covering legacy-to-current key conversions and round-trip key validation for derived and encrypted variants.

* **Chores**
  * Enabled additional async/time test support in development dependencies.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: base_layer/transaction_components/src/key_manager/key_id.rs [hunk 1]
```diff
@@ -191,6 +191,9 @@ impl FromStr for TariKeyId {
                     if parts.len() < 3 {
                         return Err("Wrong derived format".to_string());
                     };
+                    if id.contains("derived.managed.commitment mask.") {
+                        return Err("Wrong derived format".to_string());
+                    };
```
Comment (SWvheerden) [inline base_layer/transaction_components/src/key_manager/key_id.rs]:
```suggestion

```
we should not put special legacy stuff here

File: base_layer/transaction_key_manager/Cargo.toml [hunk 2]
```diff
@@ -37,7 +37,7 @@ strum = "0.22"
 strum_macros = "0.22"
 serde = { workspace = true, features = ["derive"] }
 rand = { workspace = true }
-tokio = { workspace = true, features = ["sync"] }
+tokio = { workspace = true, features = ["sync", "time"] }
```
Comment (SWvheerden) [inline base_layer/transaction_key_manager/Cargo.toml]: why this change

Comment (hansieodendaal) [reply base_layer/transaction_key_manager/Cargo.toml]: When running the added unit test
```rust
error[E0432]: unresolved import `tokio::time`
   --> base_layer\transaction_key_manager\src\storage\sqlite_db\mod.rs:38:12
    |
 38 | use tokio::time::Instant;
    |            ^^^^ could not find `time` in `tokio`
```

File: base_layer/transaction_components/src/key_manager/key_id.rs (hunk 1 above)
Comment (SWvheerden) [reply base_layer/transaction_components/src/key_manager/key_id.rs]: you can change this to be more correct, and check that the second is actually a valid value. 
Derived key are `derived.X` where X = valid tari key id. 
So  in essence you can check that parts[1..].to_string = valid key id

File: base_layer/transaction_key_manager/Cargo.toml (hunk 2 above)
Comment (SWvheerden) [reply base_layer/transaction_key_manager/Cargo.toml]: this ` use tokio::time::Instant;` is not added anywhere in the change dif, nor is there is a change here `base_layer\transaction_key_manager\src\storage\sqlite_db\mod.rs:38:12` in the change diff?

And IF this is required it should be a dev dependancy

**Review by SWvheerden — APPROVED** [review]
