### PR TITLE
Fix block validation failure in Windows for Rust tool-chain `nightly-2020-06-10`

### LINKED ISSUE #2022: Rust toolchain `nightly-2020-06-10` causing block validation in Windows to fail.
**Describe the bug**
Commit df95cee73812689bbae77bfb547c1d73a49635d4 introduced a bug in Windows builds that resulted in blocks 9182, 30335, 33923 and 34947 failing validation tests. e,g,:
```
2020-06-18 11:39:51.632946300 [c::bn::comms_interface::inbound_handler] WARN  Block #33923 
   (3a541cf21e19650697d8d785ba9b5f38e86868af94a7fca4adec3c3bcf93aef1) validation failed: ValidationError { source: 
   TransactionError(ValidationError("Sum of inputs and outputs did not equal sum of kernels with fees")) }
```
This originates from `fn validate_kernel_sum(...)` in `aggregated_body.rs`, as `fn sum_kernels(...)` returns the wrong result.
The problem is caused by updating Rust toolchain to `nightly-2020-06-10` from `nightly-2020-01-08`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Ceck out commit hash ab70a86f5f17b85fa078194896a431bfbdc90246 from `development` branch dated `2020/06/24 12:22:24`
1. Run `cargo test -p tari_core --test regression_tests`

**Expected behaviour**
When using Rust toolchain `nightly-2020-06-10` all tests should pass:
```
running 4 tests
test test_block_33923 ... ok
test test_block_34947 ... ok
test test_block_30335 ... ok
test test_block_9182 ... ok
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Windows 10

**Smartphone (please complete the following information):**
 - n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by hansieodendaal**
## Description

1. Commit df95cee73812689bbae77bfb547c1d73a49635d4 introduced a bug in Windows builds that resulted in certain blocks failing validation tests. The cause 
was traced to inconsistent implementation of the `std::f64::powi` function in certain Rust toolchains, where 
the Tari Windows code would give a slightly different floating-point result than Linux. This affected the 
missionSchedule::block_reward calculation, which caused block validation for certain block numbers to fail. 
The solution was to use crate `num::pow` for the power calculation.
(See related Rust issue: https://github.com/rust-lang/rust/issues/73920)

2. Changed two other instances where `std::f64::powi` were used.

Example, 
```
std::f64::powi(0.9999995604090385, 9182) => 0.9959718099156295 expected, but returns 0.9959718099154268
```
results in
```
EmissionSchedule::block_reward(9182) => 5517534590 expected, but returns 5516534589
```

This closes #2022. 

## Motivation and Context
When using Rust toolchain `nightly-2020-06-10` all block validation tests should pass, otherwise a base node will not be able to sync to the blockchain.

## How Has This Been Tested?
Tested in Windows 10 and Linux Ubuntu 18.04.4 LTS .

## Types of changes

* [X] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [X] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [X] New Tests
* [ ] Documentation

## Checklist:

* [X] I'm merging against the `development` branch.
* [X] I ran `cargo-fmt --all` before pushing.
* [X] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [X] I have added tests to cover my changes.

### CODE REVIEW

File: base_layer/core/src/transactions/helpers.rs [hunk 1]
```diff
@@ -383,7 +384,7 @@ pub fn schema_to_transaction(txns: &[TransactionSchema]) -> (Vec<Arc<Transaction
 /// ```
 pub fn display_currency(value: f64, precision: usize, separator: &str) -> String {
     let whole = value as usize;
-    let decimal = ((value - whole as f64) * 10_f64.powf(precision as f64)).round() as usize;
+    let decimal = ((value - whole as f64) * pow(10_f64, precision)).round() as usize;
```
Comment (stringhandler) [inline base_layer/core/src/transactions/helpers.rs:387]:
```suggestion
    let decimal = ((value - whole as f64) * pow(10, precision)).round() as usize;
```

Comment (hansieodendaal) [reply base_layer/core/src/transactions/helpers.rs:387]: It wants a safe cast to f64, thus either `10_f64` or `10 as f64`

**Review by stringhandler — APPROVED** [review]
