### PR TITLE
fix: add actual fee to memo field

### LINKED ISSUE #7466: Different network fees displayed for the same transaction when viewed in the sender vs. receiver wallet
**Describe the bug**
The console wallet (_and TU wallet_) displays different fees for outbound and inbound transactions for the same transaction viewed in the sender and receiver wallets. It seems the outbound shows the correct fee, and the inbound shows 1uT.

_(Picked up by user `deniz` on Discord - see ticket https://discord.com/channels/892738558316662855/1410185042323308564)_

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a sender and receiver wallet.
2. Send a small amount transaction from the sender to the receiver.
3. Wait for the transactions to be mined and compare the fees.

**Expected behaviour**
Fees should be displayed as the same (actual) amount when viewing the same transaction in the sender's or receiver's wallet.

**Screenshots**

### Outbound

Image

### Inbound

Image

**Desktop (please complete the following information):**
 - Windows 11

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by hansieodendaal**
Description
---
We need to know the actual fee before we can create the memo field, but the memo field is used in the fee calculation. This PR added the actual fee to the memo field by changing the encrypted data, which includes the memo field, after it became known in the builder during build.
Also reduced spam logs in `sqlite_connection_pool.rs`

Closes #7466.

Motivation and Context
---
See #7466.

How Has This Been Tested?
---
- Expanded multiple unit tests to include testing the fee embedded in the memo field in the finalised transaction.

- System-level testing succeeded.

image
image

What process can a PR reviewer use to test or verify this change?
---
- Code review.
- System-level testing.

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

## Summary by CodeRabbit

* **New Features**
  * Dynamic fee estimation is now applied across sends (including multisend, one-sided, and multisig), and memos/payment metadata reflect computed fees.
  * Per-recipient optional recovery/encryption key support added for improved payment recovery handling.
* **Bug Fixes**
  * Fewer fee mismatches during funding and multi-destination sends; discrepancies are logged for diagnosis.
* **Tests**
  * End-to-end tests decrypt and verify embedded payment/fee data to ensure finalized fees match recorded values.
* **Chores**
  * More targeted timing and fee-comparison logging added.

### CODE REVIEW

**Review by SWvheerden — CHANGES_REQUESTED** [review]
I dont think this is the best approach here, 
We are forcing the person to call estimate fee, to update the fee correctly in each output. I dont think this is covered correctly in each transaction type. 


We can do this much simpler by just updating the payment_id right before we finish the transaction with the actual fee inside the builder, and then we dont have to update it everywhere.

**Comment by hansieodendaal** [comment]
This cannot be done inside the builder, as  `TransactionBuilder::add_stealth_recipient(..)` needs it to exist before `TransactionBuilder::build()` can be called.

All instances in `TransactionService` that constructs a transaction are covered.

**Comment by SWvheerden** [comment]
And the multisig and offline signing, they are not covered.

File: base_layer/transaction_components/src/transaction_builder/builder.rs [hunk 1]
```diff
@@ -682,12 +684,106 @@ where KM: TransactionKeyManagerInterface
         ))
     }
 
+    // Helper function to change the payet_id and encrypted data if the fee has changed due to a change output
```
Comment (SWvheerden) [inline base_layer/transaction_components/src/transaction_builder/builder.rs]:
```suggestion
    // Helper function to change the memofield and encrypted data if the fee has changed due to a change output
```

File: base_layer/transaction_components/src/transaction_builder/builder.rs [hunk 2]
```diff
@@ -682,12 +684,106 @@ where KM: TransactionKeyManagerInterface
...
+    async fn change_encrypted_data_if_fee_changed(
+        key_manager: &KM,
+        output_pair: &mut OutputPair,
+        recipient_address: &TariAddress,
+        final_fee: MicroMinotari,
+    ) -> Result<(), TransactionBuilderError> {
+        let mut payment_id = output_pair.output.payment_id().clone();
```
Comment (SWvheerden) [inline base_layer/transaction_components/src/transaction_builder/builder.rs]:
```suggestion
        let mut memofield  = output_pair.output.payment_id().clone();
```

File: base_layer/transaction_components/src/transaction_builder/builder.rs [hunk 3]
```diff
@@ -682,12 +684,106 @@ where KM: TransactionKeyManagerInterface
...
+                        .sender_offset_key_id
+                        .as_ref()
+                        .ok_or(TransactionBuilderError::SenderOffsetKeyIdMissing)?,
+                    recipient_address
+                        .public_view_key()
+                        .ok_or(TransactionBuilderError::InvalidAddressNoViewKey)?,
+                )
+                .await?;
+            let encryption_private_key = shared_secret_to_output_encryption_key(&shared_secret)?;
+            let encryption_key = key_manager.import_key(encryption_private_key.clone(), None).await?;
```
Comment (SWvheerden) [inline base_layer/transaction_components/src/transaction_builder/builder.rs]:
```suggestion
           
            let encryption_key =  TariKeyId::DHEncryptedData {
            private_key: sender_offset_private_key.key_id.clone().into(),
            public_key: destination
                .public_view_key()
                .ok_or(TransactionBuilderError::InvalidAddressNoViewKey)?
                .clone(),
        };
```

File: base_layer/wallet/src/transaction_service/service.rs [hunk 4]
```diff
@@ -1258,13 +1264,20 @@ where
...
                     .await?;
 
                 let fee = tx.body.get_total_fee()?;
+                if fee_estimate != fee {
+                    warn!(
+                        target: LOG_TARGET,
+                        "Fee estimate in memo field {} does not match actual fee {} for multisig UTXO creation",
+                        fee_estimate, fee
+                    );
+                }
```
Comment (SWvheerden) [inline base_layer/wallet/src/transaction_service/service.rs]:
```suggestion
```
Why add an if here for just logging this? The builder will fix this, so this if will never be hit?

File: base_layer/wallet/src/transaction_service/service.rs [hunk 5]
```diff
@@ -1984,6 +1998,13 @@ where
 
         let tx = finalized.transaction.clone();
         let fee = finalized.fee;
+        if fee_estimate != fee {
+            warn!(
+                target: LOG_TARGET,
+                "Fee estimate in memo field {} does not match actual fee {} for send SHA atomic swap transaction",
+                fee_estimate, fee
+            );
+        }
```
Comment (SWvheerden) [inline base_layer/wallet/src/transaction_service/service.rs]:
```suggestion
```

File: base_layer/wallet/src/transaction_service/service.rs [hunk 6]
```diff
@@ -2112,6 +2138,13 @@ where
 
         let tx = finalized.transaction.clone();
         let fee = finalized.fee;
+        if fee_estimate != fee {
+            warn!(
+                target: LOG_TARGET,
+                "Fee estimate in memo field {} does not match actual fee {} for send one-sided or stealth transaction",
+                fee_estimate, fee
+            );
+        }
```
Comment (SWvheerden) [inline base_layer/wallet/src/transaction_service/service.rs]:
```suggestion
```

File: base_layer/wallet/src/transaction_service/service.rs [hunk 7]
```diff
@@ -2381,7 +2442,7 @@ where
                 .add_sender_address(
                     self.resources.one_sided_tari_address.clone(),
                     true,
-                    fee_per_gram,
+                    fee_in_memo.take().unwrap_or(MicroMinotari::zero()),
```
Comment (SWvheerden) [inline base_layer/wallet/src/transaction_service/service.rs]: Why put it in an option?
This take will put the estimate in the first one, and every subsequent one will be 0

File: base_layer/wallet/src/transaction_service/service.rs [hunk 8]
```diff
@@ -2429,7 +2473,14 @@ where
...
 
         let tx = finalized.transaction.clone();
-        let fee = finalized.fee;
+        if fee_estimate != finalized.fee {
+            debug!(
+                target: LOG_TARGET,
+                "Fee estimate in memo field {} does not match actual fee {} for send_many_one_sided_transactions",
+                fee_estimate, finalized.fee
+            );
+        }
```
Comment (SWvheerden) [inline base_layer/wallet/src/transaction_service/service.rs]:
```suggestion
```

File: base_layer/transaction_components/src/transaction_builder/builder.rs [hunk 9]
```diff
@@ -682,12 +684,106 @@ where KM: TransactionKeyManagerInterface
...
+
+            let custom_recovery_key_id = if key_manager
```
Comment (SWvheerden) [inline base_layer/transaction_components/src/transaction_builder/builder.rs]: why not save this key on the walletoutput, then you dont have to guess it.

**Review by SWvheerden — CHANGES_REQUESTED** [review]

File: base_layer/wallet/src/transaction_service/service.rs (hunk 7 above)
Comment (hansieodendaal) [reply base_layer/wallet/src/transaction_service/service.rs]: Yes, that is the intent. Only the real transaction has a fee, the total fee. The other transactions are all faux transactions and did not attract a fee. Adding the average fee or total fee to the real transaction and faux transactions is not correct.

File: base_layer/transaction_components/src/transaction_builder/builder.rs (hunk 9 above)
Comment (hansieodendaal) [reply base_layer/transaction_components/src/transaction_builder/builder.rs]: Good suggestion. As per the discussion, I saved it to the `OutputPair` instead; this simplified the code in this function considerably.

File: base_layer/wallet/src/transaction_service/service.rs (hunk 7 above)
Comment (hansieodendaal) [reply base_layer/wallet/src/transaction_service/service.rs]: As per discussion, I am going to change this to add the total fee to all faux transactions.

File: base_layer/transaction_components/src/transaction_builder/builder.rs [hunk 10]
```diff
@@ -682,12 +701,62 @@ where KM: TransactionKeyManagerInterface
...
+                        .as_ref()
+                        .ok_or(TransactionBuilderError::SenderOffsetKeyIdMissing)?,
+                    memo_field,
+                    key_manager,
+                )
+                .await?;
+        }
+
+        Ok(())
+    }
```
[the remark this answers is not in the document]
Comment (hansieodendaal) [reply base_layer/transaction_components/src/transaction_builder/builder.rs:752]: This code may not change the memo field in that way - it may only correct the fee if the memo includes it and it is wrong.

File: base_layer/wallet/src/transaction_service/service.rs [hunk 11]
```diff
@@ -2462,23 +2484,25 @@ where
...
             tx_ids.push(new_tx_id);
             let completed_tx = CompletedTransaction::new_with_output_hashes(
                 new_tx_id,
                 self.resources.one_sided_tari_address.clone(),
-                destination.0.clone(),
-                destination.1,
-                fee,
+                address.clone(),
+                amount,
+                MicroMinotari::zero(),
```
Comment (SWvheerden) [inline base_layer/wallet/src/transaction_service/service.rs]: Put the finalized fee here

**Review by SWvheerden — CHANGES_REQUESTED** [review]

File: base_layer/wallet/src/transaction_service/service.rs (hunk 11 above)
Comment (SWvheerden) [inline base_layer/wallet/src/transaction_service/service.rs]:
```suggestion
                finalized.fee,
```
