### PR TITLE
fix!: payref migration and indexes, add grpc query via output hash

### LINKED ISSUE #7263: [base node grpc] Not all requested outputs are returned via payref
Once an output has been spent, the payref is deleted.

### PR DESCRIPTION
**Pull request by hansieodendaal**
Description
---
- Added gRPC method to retrieve output information via output hash
- Updated the gRPC payref search to return spent and unspent output information
- Added migration to rebuild payref indexes due to missing payrefs (_added periodic call to `LMDBStore::resize_if_required`_)
- Fixed error in lmdb migration counter where it recorded a higher version done than what it should

Fixes #7263 

Motivation and Context
---
- Payref information was deleted when the outputs were spent.
- With migrations, payref information was only created for the current output set, not all outputs.
- Payref lookups for spent outputs were not possible.
- Output and payref information was not possible via output hash.

How Has This Been Tested?
---
- New lmdb migration tested at the system level for fresh and existing base nodes.
- New gRPC method system-level testing [_tested with block explorer upgrade_].
- General system-level testing.

Fresh base node with a restart afterwards
```rust
2025-06-27 09:09:24.013840800 [c::cs::lmdb_db::lmdb_db] INFO  [MIGRATIONS] Blockchain database is at v0 (required version: 5)
2025-06-27 09:09:24.013873800 [c::cs::lmdb_db::lmdb_db] INFO  [MIGRATIONS] v1: No accumulated difficulty found for block height 14999
2025-06-27 09:09:24.013877800 [c::cs::lmdb_db::lmdb_db] INFO  [MIGRATIONS] v1: No migration to perform for version network
2025-06-27 09:09:24.013883100 [c::cs::lmdb_db::lmdb_db] INFO  [MIGRATIONS] v2: Starting PayRef migration
2025-06-27 09:09:24.013899700 [c::cs::lmdb_db::lmdb_db] INFO  [MIGRATIONS] v2: Cleared PayRef index
2025-06-27 09:09:24.038671500 [c::cs::lmdb_db::lmdb_db] INFO  [MIGRATIONS] v2: PayRef index rebuild completed
2025-06-27 09:09:24.038693200 [c::cs::lmdb_db::lmdb_db] INFO  [MIGRATIONS] Migrated database from version 2 to version 3
2025-06-27 09:09:24.039646900 [c::cs::lmdb_db::lmdb_db] INFO  [MIGRATIONS] Migrated database from version 3 to version 4
2025-06-27 09:09:24.040506700 [c::cs::lmdb_db::lmdb_db] INFO  [MIGRATIONS] Migrated database from version 4 to version 5
2025-06-27 09:10:24.526178200 [c::cs::lmdb_db::lmdb_db] INFO  [MIGRATIONS] Blockchain database is at v5 (required version: 5)
```

What process can a PR reviewer use to test or verify this change?
---
- Code review.
- System-level testing.

Breaking Changes
---

- [ ] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [X] Other - Please specify

BREAKING CHANGE: 
- A new base node gRPC method `SearchPaymentReferencesViaOutputHash` was added that returns a stream of `PaymentReferenceResponse`.
- The gRPC `PaymentReferenceResponse` was also updated to return the spent timestamp and output hash additionally.

## Summary by CodeRabbit

* **New Features**
  * Added a new gRPC method to search payment references by output hash, providing detailed mined and spent information for outputs.
  * Expanded response data to include spent timestamps and output hashes for enhanced transaction tracing.

* **Refactor**
  * Unified and extended backend logic for fetching mined information by payment reference or output hash.
  * Improved migration and index handling for payment references to ensure data consistency, including genesis block coverage.

* **Documentation**
  * Clarified field comments and updated configuration files to reflect new gRPC capabilities.

* **Style**
  * Updated test and code comments for clarity and consistency.

### CODE REVIEW

File: base_layer/core/src/chain_storage/blockchain_database.rs [hunk 1]
```diff
@@ -454,10 +454,22 @@ where B: BlockchainBackend
...
     }
 
-    /// Returns a copy of the output mined info by payment reference
-    pub fn fetch_output_by_payref(&self, payref: FixedHash) -> Result<Option<OutputMinedInfo>, ChainStorageError> {
+    /// Returns a copy of the mined info by payment reference
+    pub fn fetch_mined_info_by_payref(&self, payref: FixedHash) -> Result<MinedInfo, ChainStorageError> {
         let db = self.db_read_access()?;
-        db.fetch_output_by_payref(&payref)
+        db.fetch_mined_info_by_payref(&payref)
+    }
```
[the remark this answers is not in the document]
Comment (hansieodendaal) [reply base_layer/core/src/chain_storage/blockchain_database.rs]: See `MinedInfo` below - it consists of options
```
pub struct MinedInfo {
    pub input: Option<InputMinedInfo>,
    pub output: Option<OutputMinedInfo>,
}
```

**Review by SWvheerden — CHANGES_REQUESTED** [review]
I am against this appraoch
We already have all info needed to calculate this, we don't need to store another index, 
And on the application layer, you need to do two lookups and not one. 

use this function: `fetch_output_in_txn`
it contains all the info needed for the payref.

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 2]
```diff
@@ -3150,41 +3222,48 @@ fn run_migrations(db: &mut LMDBDatabase) -> Result<(), ChainStorageError> {
...
+        // Lets update the migration version
         {
             let txn = db.write_transaction()?;
             info!(target: LOG_TARGET, "Migrated database to version {}", MIGRATION_VERSION);
             lmdb_replace(
                 &txn,
                 &db.metadata_db,
                 &k.as_u32(),
-                &MetadataValue::MigrationVersion(migrate_from_version + 1),
+                &MetadataValue::MigrationVersion(max(migrate_from_version + 1, MIGRATION_VERSION)),
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]:
```suggestion
                &MetadataValue::MigrationVersion(max(migrate_from_version , MIGRATION_VERSION)),
```
thats why the migration ended in a 4 and not the correct 3, we can just skip 4 and

Comment (hansieodendaal) [reply base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: I solved this in a slightly differtent manner - system-level tested and working

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 3]
```diff
@@ -608,13 +611,7 @@ impl LMDBDatabase {
...
         // Generate PayRef and add to index
         let payref = Self::generate_payment_reference_for_output(header_hash, &output_hash);
-        lmdb_insert(
-            txn,
-            &self.payref_to_output_index,
-            payref.as_slice(),
-            &output_hash,
-            "payref_to_output_index",
-        )?;
+        lmdb_replace(txn, &self.payref_to_output_index, payref.as_slice(), &output_hash, None)?;
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]:
```suggestion
        lmdb_insert(txn, &self.payref_to_output_index, payref.as_slice(), &output_hash, None)?;
```
this will hide errors

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 4]
```diff
@@ -3117,10 +3112,16 @@ fn run_migrations(db: &mut LMDBDatabase) -> Result<(), ChainStorageError> {
             }
             txn.commit()?;
         }
+
+        // MIGRATION: Accumulated difficulty migration - blockchain rewind to last known good accumulated difficulty
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]:
```suggestion
        // MIGRATION: Total Accumulated difficulty migration - blockchain rewind to last known good accumulated difficulty
```

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 5]
```diff
@@ -3132,59 +3133,78 @@ fn run_migrations(db: &mut LMDBDatabase) -> Result<(), ChainStorageError> {
...
-            info!(target: LOG_TARGET, "PayRef index rebuild completed");
+
+            payref_index_done = true;
+            info!(target: LOG_TARGET, "[MIGRATIONS] v{}: PayRef index rebuild completed", migrate_from_version);
         }
-        // lets update the migration version
+
+        // Lets update the migration version
         {
+            let migrated_to_version = migrate_from_version + 1;
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs:3194]:
```suggestion
            let migrated_to_version = migrate_from_version ;
```
was the +1 not a problem

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 6]
```diff
@@ -3132,59 +3133,78 @@ fn run_migrations(db: &mut LMDBDatabase) -> Result<(), ChainStorageError> {
...
-                    // No chain data, skip PayRef rebuild
-                    drop(read_txn);
-                    continue;
-                },
-            };
+            let chain_height = fetch_chain_height(&read_txn, &db.metadata_db).unwrap_or(0);
             drop(read_txn);
-            // we need to clear the payref index first as they might now bw wrong
+
+            // Clear the payref index first as they might now be wrong
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: we dont need to delete it

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 7]
```diff
@@ -3287,33 +3307,62 @@ fn get_correct_accumulated_difficulty() -> Vec<(u64, U512)> {
...
+            .iter()
+            .map(|o| TransactionOutputRowData {
+                output: o.clone(),
+                header_hash,
+                hash: o.hash(),
+                mined_height: 0,
+                mined_timestamp,
+            })
+            .collect::<Vec<_>>();
+        (header_hash, outputs)
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: this does not seem correct, you are double-processing the block here. 
If the block chain is empty, this is going to be 0 by the unwrap or 0 above, which means the gen block still needs to be processed. If its actually 0, it should be in the outputs, and we can recall them from that. 
Is this migration the reason you changed the lmdb_insert to lmdb_replace?

**Review by SWvheerden — CHANGES_REQUESTED** [review]

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs (hunk 5 above)
Comment (hansieodendaal) [reply base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs:3194]: No, it was the combination of the `migrate_from_version` counter, where it ended and what is deemed as the version we have achieved - to make this clear I introduced the `migrated_to_version` variable and changed `last_migrated_version..=MIGRATION_VERSION` to `last_migrated_version..MIGRATION_VERSION`. 

If we use `last_migrated_version..=MIGRATION_VERSION` the start and end logic is not 100%  as it would revisit the loop if we are on v4 and we should be on v4 - now it will only go into the loop if a migration is needed.

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs (hunk 7 above)
Comment (hansieodendaal) [reply base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: Yes, that is the issue, double processing, and that was the reason for the replace

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs (hunk 6 above)
Comment (hansieodendaal) [reply base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: Agreed, a remnant of the previous code - replace will update it anyway.

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs (hunk 3 above)
Comment (hansieodendaal) [reply base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: Agreed, this was due to double processing the genesis block, once in the migration and then when building the chain.

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 8]
```diff
@@ -1084,16 +1057,15 @@ impl LMDBDatabase {
...
                 &self.txos_hash_to_index_db,
                 utxo.hash.as_slice(),
                 "txos_hash_to_index_db",
             )?;
 
-            let output_hash = utxo.output.hash();
-
             // Clean up PayRef index for this output during reorg
             // Only clean PayRef if output was actually created (not spent in same block, not burned)
             let should_cleanup_payref =
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs]: this should be updated as well

File: base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs [hunk 9]
```diff
@@ -3164,27 +3182,33 @@ fn run_migrations(db: &mut LMDBDatabase) -> Result<(), ChainStorageError> {
...
-                let txn = db.write_transaction()?;
-                lmdb_clear(&txn, &db.payref_to_output_index)?;
-                txn.commit()?;
-                info!(target: LOG_TARGET, "Cleared PayRef index");
-            }
+
             for height in 0..=chain_height {
+                if height % 100 == 0 {
+                    unsafe {
+                        LMDBStore::resize_if_required(&db.env, &db.env_config, None)?;
```
Comment (SWvheerden) [inline base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs:3182]: I think this is somewhat in the correct order, but call this between all migrations, 
And make this: every X block, 100 is too few...
a payref index entry is 32*2 bytes, default increase is 128mb.

File: applications/minotari_app_grpc/proto/base_node.proto [hunk 10]
```diff
@@ -591,20 +594,24 @@ message SearchPaymentReferencesRequest {
...
     // Whether this output has been spent
     bool is_spent = 6;
-    // Height where output was spent (if spent)
+    // Height where output was spent - will be 0 for unspent outputs
     uint64 spent_height = 7;
-    // Block hash where output was spent (if spent)
+    // Block hash where output was spent - will be empty for unspent outputs
     bytes spent_block_hash = 8;
-    // Transaction output amount will be 0 for non set a
+    // Minimum value promise - will be 0 for spent outputs
```
Comment (SWvheerden) [inline applications/minotari_app_grpc/proto/base_node.proto]: I dont think this comment is correct?

**Review by SWvheerden — CHANGES_REQUESTED** [review]
Looking good, 
There is a missed if statement that needs updating, and I think we need to update the migration thing as noted.

File: applications/minotari_app_grpc/proto/base_node.proto (hunk 10 above)
Comment (hansieodendaal) [reply applications/minotari_app_grpc/proto/base_node.proto]: We populate it with 0 for spent outputs as we do not know what it is

**Comment by MCozhusheck** [comment]
Code is looking great, tested manually and search by output hash `99fa77666a4c06bbdaebf3c9fad441e1cd82116df16e9754a7fae57b229a34a0` (first output in block 15756) and found exact payref https://explore.tari.com/blocks/15756
Tested for multiple inputs and invalid inputs. In a single input that is invalid I got error response but in case of multiple inputs where some were invalid I got response only for valid one.

**Review by MCozhusheck — APPROVED** [review]

File: applications/minotari_app_grpc/proto/base_node.proto [hunk 11]
```diff
@@ -591,20 +594,24 @@ message SearchPaymentReferencesRequest {
...
     // Whether this output has been spent
     bool is_spent = 6;
-    // Height where output was spent (if spent)
+    // Height where output was spent - will be 0 for unspent outputs as it is not applicable
     uint64 spent_height = 7;
-    // Block hash where output was spent (if spent)
+    // Block hash where output was spent - will be empty for unspent outputs
     bytes spent_block_hash = 8;
-    // Transaction output amount will be 0 for non set a
+    // Minimum value promise - will be 0 for spent outputs as we do not track this for spent outputs
```
Comment (hansieodendaal) [inline applications/minotari_app_grpc/proto/base_node.proto]:
```suggestion
    // Minimum value promise
```

File: applications/minotari_app_grpc/proto/base_node.proto [hunk 12]
```diff
@@ -591,20 +594,24 @@ message SearchPaymentReferencesRequest {
 message PaymentReferenceResponse {
     // The payment reference that was found
     string payment_reference_hex = 1;
-    // Block height where the output was mined
+    // Block height where the output was mined - will be 0 for spent outputs as it is not applicable
```
Comment (SWvheerden) [inline applications/minotari_app_grpc/proto/base_node.proto]: and these all?

Comment (hansieodendaal) [inline applications/minotari_app_grpc/proto/base_node.proto]:
```suggestion
    // Block height where the output was mined
```

File: applications/minotari_app_grpc/proto/base_node.proto [hunk 13]
```diff
@@ -591,20 +594,24 @@ message SearchPaymentReferencesRequest {
...
     uint64 block_height = 2;
-    // Block hash where the output was mined
+    // Block hash where the output was mined - will be empty for spent outputs as it is not applicable
```
Comment (hansieodendaal) [inline applications/minotari_app_grpc/proto/base_node.proto]:
```suggestion
    // Block hash where the output was mined
```

File: applications/minotari_app_grpc/proto/base_node.proto [hunk 14]
```diff
@@ -591,20 +594,24 @@ message SearchPaymentReferencesRequest {
...
     bytes block_hash = 3;
-    // Timestamp when the output was mined
+    // Timestamp when the output was mined - will be 0 for spent outputs as it is not applicable
```
Comment (hansieodendaal) [inline applications/minotari_app_grpc/proto/base_node.proto]:
```suggestion
    // Timestamp when the output was mined
```

File: applications/minotari_app_grpc/proto/base_node.proto [hunk 15]
```diff
@@ -597,14 +600,18 @@ message PaymentReferenceResponse {
     bytes block_hash = 3;
     // Timestamp when the output was mined
     uint64 mined_timestamp = 4;
-    // Output commitment (32 bytes)
+    // Output commitment (32 bytes) - will be empty if output was spent as we do not track this for spent outputs
```
Comment (hansieodendaal) [inline applications/minotari_app_grpc/proto/base_node.proto]:
```suggestion
    // Output commitment (32 bytes)
```

**Review by SWvheerden — APPROVED** [review]
