### PR TITLE
fix: seed peer connections kept open

### LINKED ISSUE #7558: Seed peer connections kept open
We are still keeping alive the seed peers connections:

Image

Look at the attached screenshot, those connections are open for more than an hour, and they are all outbound

We need to find out why they are not being closed, or redialed.

### PR DESCRIPTION
**Pull request by martinserts**
Description
---

Bugs fixed:
- incorrect identification of idle peers (`substream_count() > 2` -> `substream_count() < 3`)
- `ConnectivityManager` was using `random_pool_refresh_interval` (default 2 hrs) instead of intended `update_interval` (default 2 minutes) to fire cleanup logic
- broken seed detection - `get_seed_peers` checked exact equality (`flags == SEED`). If a peer had multiple flags (`SEED | COMPACT`), it would be ignored.

New features / changes:
- Seed nodes are now forcibly disconnected after a grace period, provided the node has sufficient other connections (`> min_connectivity`)
- Added config entry `max_seed_peer_age` (default 15 minutes)
- `update_peer_sql` will persist `flags` and `features` as well

Closes #7558

Motivation and Context
---

It was noticed, that seed connections where kept open for a long time.

How Has This Been Tested?
---

Added a test.

And tested manually:

```
>> list-connections

Base Nodes
----------

NodeId                     | Public Key                                                       | Address                                                                | Direction | Age     | User Agent                | Seed | Info                                  
-------------------------- | ---------------------------------------------------------------- | ---------------------------------------------------------------------- | --------- | ------- | ------------------------- | ---- | ------------------------------------- 
ace05844c9c9723a8597682be3 | 1e08628960f75b7e324f010b2ee609a9e28097e9101f4d769d474a38b6ee2d76 | /ip4/51.83.102.25/tcp/18189                                            | Outbound  | 12m 33s | tari/basenode/5.3.0-pre.1 | SEED | height: 509627, hnd: 2, ss: 2, rpc: 0 
1918864cd464060b70f5158f3e | 6294d74a49720ce37f847d1da69259ac3153b66d40c319a6d44a0982245db51f | /onion3/jimpqrodmtzize3w4wilju6w6nx77ditwp5677lj5mhxlrd6v67s4qqd:18141 | Outbound  | 6m 27s  | tari/basenode/5.3.0-pre.1 |      | height: 509627, hnd: 3, ss: 2, rpc: 0 
e0e3f3a847fbf71baf30cfc79d | 7a079f2b813ddbf5e59403c80200af4137ddd8b0d3f017e2ec6b8fa2fb4f397e | /onion3/bwagn3fa7any5uig2brzbxbk7uxgf5hp2wfbpkmja2pqz37k2zn252qd:18141 | Outbound  | 12m 29s | tari/basenode/5.1.0       |      | height: 509627, hnd: 3, ss: 2, rpc: 0 
52476d7371e2d3cfdc6aa9fa8e | 6001c31cc69b7a4211bdde8a73b88a467fa6a285b2d69631b35747b2df6c7704 | /onion3/3lklntggyxiwi6b5sjwwiwkvzhsiljqyzripveh2uw5lvqarww6lyyad:18141 | Outbound  | 12m 21s | tari/basenode/5.2.0-pre.0 |      | height: 509627, hnd: 3, ss: 2, rpc: 0 
ab2fad12f448628436bcbe98d1 | 4cdfb70e0b38b60c6a3573b2870e32bc3d846419c606ea379f43650b80f38409 | /ip4/51.83.4.85/tcp/18189                                              | Outbound  | 12m 18s | tari/basenode/5.3.0-pre.1 | SEED | height: 509627, hnd: 3, ss: 2, rpc: 0 
bb8da2644a856e5d5f8a7db05c | 2ca6775cde640eff6f433c2bbdda8846e299b667317434996f388630c3b8ae04 | /onion3/a4civpppxeoryjshkezvpi6j2zj4f3pplxjxj55uzlnxaqqmr6svcsad:18141 | Outbound  | 12m 29s | tari/basenode/5.2.1-pre.2 |      | height: 509627, hnd: 3, ss: 2, rpc: 0 
d4ffef3e484b36bac72c46064a | 4e3cf7e6509d41accbed3a1098c2abf601a6b23098a03ffd992eb047e1566561 | /onion3/ngjw3rcuvpfpyg64qyqhlvjitrzq2y3r6hucrk5yqwk6uhkekqnbhead:18141 | Outbound  | 10m 12s | tari/basenode/5.2.1-pre.2 |      | height: 509627, hnd: 3, ss: 2, rpc: 0 
7 active connection(s)

Wallets
-------
No active wallet connections.
>> 
```

**when 15 minutes elapsed**

```
>> list-connections

Base Nodes
----------

NodeId                     | Public Key                                                       | Address                                                                | Direction | Age     | User Agent                | Seed | Info                                  
-------------------------- | ---------------------------------------------------------------- | ---------------------------------------------------------------------- | --------- | ------- | ------------------------- | ---- | ------------------------------------- 
1918864cd464060b70f5158f3e | 6294d74a49720ce37f847d1da69259ac3153b66d40c319a6d44a0982245db51f | /onion3/jimpqrodmtzize3w4wilju6w6nx77ditwp5677lj5mhxlrd6v67s4qqd:18141 | Outbound  | 11m 41s | tari/basenode/5.3.0-pre.1 |      | height: 509629, hnd: 3, ss: 2, rpc: 0 
bb8da2644a856e5d5f8a7db05c | 2ca6775cde640eff6f433c2bbdda8846e299b667317434996f388630c3b8ae04 | /onion3/a4civpppxeoryjshkezvpi6j2zj4f3pplxjxj55uzlnxaqqmr6svcsad:18141 | Outbound  | 17m 42s | tari/basenode/5.2.1-pre.2 |      | height: 509629, hnd: 3, ss: 2, rpc: 0 
d4ffef3e484b36bac72c46064a | 4e3cf7e6509d41accbed3a1098c2abf601a6b23098a03ffd992eb047e1566561 | /onion3/ngjw3rcuvpfpyg64qyqhlvjitrzq2y3r6hucrk5yqwk6uhkekqnbhead:18141 | Outbound  | 15m 25s | tari/basenode/5.2.1-pre.2 |      | height: 509629, hnd: 3, ss: 2, rpc: 0 
e0e3f3a847fbf71baf30cfc79d | 7a079f2b813ddbf5e59403c80200af4137ddd8b0d3f017e2ec6b8fa2fb4f397e | /onion3/bwagn3fa7any5uig2brzbxbk7uxgf5hp2wfbpkmja2pqz37k2zn252qd:18141 | Outbound  | 17m 42s | tari/basenode/5.1.0       |      | height: 509629, hnd: 3, ss: 2, rpc: 0 
ace05844c9c9723a8597682be3 | 1e08628960f75b7e324f010b2ee609a9e28097e9101f4d769d474a38b6ee2d76 | /ip4/51.83.102.25/tcp/18189                                            | Outbound  | 1m 47s  | tari/basenode/5.3.0-pre.1 | SEED | height: 509629, hnd: 3, ss: 2, rpc: 0 
52476d7371e2d3cfdc6aa9fa8e | 6001c31cc69b7a4211bdde8a73b88a467fa6a285b2d69631b35747b2df6c7704 | /onion3/3lklntggyxiwi6b5sjwwiwkvzhsiljqyzripveh2uw5lvqarww6lyyad:18141 | Outbound  | 17m 34s | tari/basenode/5.2.0-pre.0 |      | height: 509629, hnd: 3, ss: 2, rpc: 0 
ab2fad12f448628436bcbe98d1 | 4cdfb70e0b38b60c6a3573b2870e32bc3d846419c606ea379f43650b80f38409 | /ip4/51.83.4.85/tcp/18189                                              | Outbound  | 1m 47s  | tari/basenode/5.3.0-pre.1 | SEED | height: 509629, hnd: 3, ss: 2, rpc: 0 
7 active connection(s)

Wallets
-------
No active wallet connections.
>> 
```

What process can a PR reviewer use to test or verify this change?
---

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

### CODE REVIEW

File: base_layer/p2p/src/initialization.rs [hunk 1]
```diff
@@ -569,7 +569,8 @@ impl ServiceInitializer for P2pInitializer {
                 network_wire_byte: self.network.as_wire_byte(),
                 user_agent: self.user_agent.clone(),
             })
-            .with_connection_pool_refresh_interval(config.dht.connectivity.random_pool_refresh_interval)
+            .with_connection_pool_refresh_interval(config.dht.connectivity.update_interval)
```
Comment (brianp) [inline base_layer/p2p/src/initialization.rs:572]: This swaps `random_pool_refresh_interval` (default 2h) for `update_interval` (default 2min). That's a 60x increase in how often the connection pool refresh runs, which now includes seed disconnection, inactive reaping, and proactive dialing.

Was this intentional? If the goal was to make seed cleanup happen more often, it might be worth a dedicated timer for that instead of cranking the whole pool maintenance cycle. If it _is_ intentional, probably worth a note in the changelog since it'll change behavior for anyone running default configs.

File: comms/core/src/connectivity/connection_pool.rs [hunk 2]
```diff
@@ -169,7 +169,7 @@ impl ConnectionPool {
 
     pub fn get_inactive_outbound_connections_mut(&mut self, min_age: Duration) -> Vec<&mut PeerConnection> {
         self.filter_connections_mut(|conn| {
-            conn.age() > min_age && conn.handle_count() <= 1 && conn.substream_count() > 2
+            conn.age() > min_age && conn.handle_count() <= 1 && conn.substream_count() < 3
```
Comment (brianp) [inline comms/core/src/connectivity/connection_pool.rs:172]: This flips the condition from `substream_count() > 2` to `substream_count() < 3`. These aren't equivalent, the old version matched connections with 3+ substreams, the new one matches connections with 0-2 substreams.

I'm assuming this is a bug fix? The function name says "inactive" connections, and fewer substreams = more inactive makes sense. Just want to confirm the old logic was wrong.

File: comms/core/src/peer_manager/storage/database.rs [hunk 3]
```diff
@@ -1756,7 +1758,10 @@ impl PeerDatabaseSql {
         // Perform a join query to fetch peers and their addresses
         let results = peers::table
             .inner_join(multi_addresses::table.on(multi_addresses::peer_id.eq(peers::peer_id)))
-            .filter(peers::flags.eq(PeerFlags::SEED.to_i32()))
+            .filter(diesel::dsl::sql::<diesel::sql_types::Bool>(&format!(
+                "flags & {} != 0",
```
Comment (brianp) [inline comms/core/src/peer_manager/storage/database.rs:1762]: Good fix, using bitwise AND instead of exact equality means peers with `SEED | OTHER_FLAG` won't get missed. Since `PeerFlags::SEED.to_i32()` is a compile-time constant (0x01), the format string is safe here.

Minor thought: if Diesel ever adds a bitwise AND expression, it'd be nice to move off raw SQL. Not a big deal for now though.

**Review by brianp — APPROVED** [review]
Looks good. The seed peer disconnection logic is solid, the min_connectivity guard prevents over-disconnection and the proactive dialer re-includes seeds when connectivity drops below threshold. Nice test coverage for the happy path too.

I've got three clarification questions inline. None of them are blockers, just want to make sure I'm reading the intent right.

File: comms/core/src/connectivity/connection_pool.rs (hunk 2 above)
Comment (martinserts) [reply comms/core/src/connectivity/connection_pool.rs:172]: Yes, a bug fix.
This feature was from this PR - #4607

And it says:
```
only reap connections that have less than 3 substreams
```

So it was a bug.

File: base_layer/p2p/src/initialization.rs (hunk 1 above)
Comment (martinserts) [reply base_layer/p2p/src/initialization.rs:572]: This was intentional.
Binding `random_pool_refresh_interval` to 2h I think is not correct.

Internal default is 60 seconds!
See `comms/core/src/connectivity/config.rs`

```rs
connection_pool_refresh_interval: Duration::from_secs(60)
```

If node lost connection, it would wait 2 hours before proactive dialling kicks in. This restores the responsiveness (as it was initially intended I guess).

I am looking for changelog, but it seems changelogs are auto-generated here.
